//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/Zetzsche/Development/SimarisCurves/com.thoughtworks.xstream/bin/src/com/thoughtworks/xstream/converters/extended/JavaClassConverter.java
//


#line 1 "/Users/Zetzsche/Development/SimarisCurves/com.thoughtworks.xstream/bin/src/com/thoughtworks/xstream/converters/extended/JavaClassConverter.java"

#include "IOSClass.h"
#include "J2ObjC_source.h"
#include "com/thoughtworks/xstream/converters/ConversionException.h"
#include "com/thoughtworks/xstream/converters/basic/AbstractSingleValueConverter.h"
#include "com/thoughtworks/xstream/converters/extended/JavaClassConverter.h"
#include "com/thoughtworks/xstream/core/ClassLoaderReference.h"
#include "com/thoughtworks/xstream/mapper/CannotResolveClassException.h"
#include "com/thoughtworks/xstream/mapper/DefaultMapper.h"
#include "com/thoughtworks/xstream/mapper/Mapper.h"
#include "java/lang/ClassLoader.h"
#include "java/lang/Throwable.h"

@interface ComThoughtworksXstreamConvertersExtendedJavaClassConverter () {
 @public
  id<ComThoughtworksXstreamMapperMapper> mapper_;
}

@end

J2OBJC_FIELD_SETTER(ComThoughtworksXstreamConvertersExtendedJavaClassConverter, mapper_, id<ComThoughtworksXstreamMapperMapper>)


#line 29
@implementation ComThoughtworksXstreamConvertersExtendedJavaClassConverter


#line 38
- (instancetype)initWithComThoughtworksXstreamCoreClassLoaderReference:(ComThoughtworksXstreamCoreClassLoaderReference *)classLoaderReference {
  ComThoughtworksXstreamConvertersExtendedJavaClassConverter_initWithComThoughtworksXstreamCoreClassLoaderReference_(self, classLoaderReference);
  return self;
}


#line 45
- (instancetype)initWithJavaLangClassLoader:(JavaLangClassLoader *)classLoader {
  ComThoughtworksXstreamConvertersExtendedJavaClassConverter_initWithJavaLangClassLoader_(self, classLoader);
  return self;
}


#line 55
- (instancetype)initWithComThoughtworksXstreamMapperMapper:(id<ComThoughtworksXstreamMapperMapper>)mapper {
  ComThoughtworksXstreamConvertersExtendedJavaClassConverter_initWithComThoughtworksXstreamMapperMapper_(self, mapper);
  return self;
}


#line 59
- (jboolean)canConvertWithIOSClass:(IOSClass *)clazz {
  return [IOSClass_class_() isEqual:clazz];
}

- (NSString *)toStringWithId:(id)obj {
  return [((id<ComThoughtworksXstreamMapperMapper>) nil_chk(mapper_)) serializedClassWithIOSClass:((IOSClass *) check_class_cast(obj, [IOSClass class]))];
}

- (id)fromStringWithNSString:(NSString *)str {
  @try {
    return [((id<ComThoughtworksXstreamMapperMapper>) nil_chk(mapper_)) realClassWithNSString:str];
  }
  @catch (
#line 70
  ComThoughtworksXstreamMapperCannotResolveClassException *e) {
    @throw new_ComThoughtworksXstreamConvertersConversionException_initWithNSString_withJavaLangThrowable_(JreStrcat("$$", @"Cannot load java class ", str), [((ComThoughtworksXstreamMapperCannotResolveClassException *) nil_chk(e)) getCause]);
  }
}

+ (const J2ObjcClassInfo *)__metadata {
  static const J2ObjcMethodInfo methods[] = {
    { "initWithComThoughtworksXstreamCoreClassLoaderReference:", "JavaClassConverter", NULL, 0x1, NULL, NULL },
    { "initWithJavaLangClassLoader:", "JavaClassConverter", NULL, 0x1, NULL, NULL },
    { "initWithComThoughtworksXstreamMapperMapper:", "JavaClassConverter", NULL, 0x4, NULL, NULL },
    { "canConvertWithIOSClass:", "canConvert", "Z", 0x1, NULL, NULL },
    { "toStringWithId:", "toString", "Ljava.lang.String;", 0x1, NULL, NULL },
    { "fromStringWithNSString:", "fromString", "Ljava.lang.Object;", 0x1, NULL, NULL },
  };
  static const J2ObjcFieldInfo fields[] = {
    { "mapper_", NULL, 0x2, "Lcom.thoughtworks.xstream.mapper.Mapper;", NULL, NULL,  },
  };
  static const J2ObjcClassInfo _ComThoughtworksXstreamConvertersExtendedJavaClassConverter = { 2, "JavaClassConverter", "com.thoughtworks.xstream.converters.extended", NULL, 0x1, 6, methods, 1, fields, 0, NULL, 0, NULL, NULL, NULL };
  return &_ComThoughtworksXstreamConvertersExtendedJavaClassConverter;
}

@end


#line 38
void ComThoughtworksXstreamConvertersExtendedJavaClassConverter_initWithComThoughtworksXstreamCoreClassLoaderReference_(ComThoughtworksXstreamConvertersExtendedJavaClassConverter *self, ComThoughtworksXstreamCoreClassLoaderReference *classLoaderReference) {
  (void) ComThoughtworksXstreamConvertersExtendedJavaClassConverter_initWithComThoughtworksXstreamMapperMapper_(self, new_ComThoughtworksXstreamMapperDefaultMapper_initWithComThoughtworksXstreamCoreClassLoaderReference_(classLoaderReference));
}


#line 38
ComThoughtworksXstreamConvertersExtendedJavaClassConverter *new_ComThoughtworksXstreamConvertersExtendedJavaClassConverter_initWithComThoughtworksXstreamCoreClassLoaderReference_(ComThoughtworksXstreamCoreClassLoaderReference *classLoaderReference) {
  ComThoughtworksXstreamConvertersExtendedJavaClassConverter *self = [ComThoughtworksXstreamConvertersExtendedJavaClassConverter alloc];
  ComThoughtworksXstreamConvertersExtendedJavaClassConverter_initWithComThoughtworksXstreamCoreClassLoaderReference_(self, classLoaderReference);
  return self;
}


#line 45
void ComThoughtworksXstreamConvertersExtendedJavaClassConverter_initWithJavaLangClassLoader_(ComThoughtworksXstreamConvertersExtendedJavaClassConverter *self, JavaLangClassLoader *classLoader) {
  (void) ComThoughtworksXstreamConvertersExtendedJavaClassConverter_initWithComThoughtworksXstreamCoreClassLoaderReference_(self, new_ComThoughtworksXstreamCoreClassLoaderReference_initWithJavaLangClassLoader_(classLoader));
}


#line 45
ComThoughtworksXstreamConvertersExtendedJavaClassConverter *new_ComThoughtworksXstreamConvertersExtendedJavaClassConverter_initWithJavaLangClassLoader_(JavaLangClassLoader *classLoader) {
  ComThoughtworksXstreamConvertersExtendedJavaClassConverter *self = [ComThoughtworksXstreamConvertersExtendedJavaClassConverter alloc];
  ComThoughtworksXstreamConvertersExtendedJavaClassConverter_initWithJavaLangClassLoader_(self, classLoader);
  return self;
}


#line 55
void ComThoughtworksXstreamConvertersExtendedJavaClassConverter_initWithComThoughtworksXstreamMapperMapper_(ComThoughtworksXstreamConvertersExtendedJavaClassConverter *self, id<ComThoughtworksXstreamMapperMapper> mapper) {
  (void) ComThoughtworksXstreamConvertersBasicAbstractSingleValueConverter_init(self);
  
#line 56
  self->mapper_ = mapper;
}


#line 55
ComThoughtworksXstreamConvertersExtendedJavaClassConverter *new_ComThoughtworksXstreamConvertersExtendedJavaClassConverter_initWithComThoughtworksXstreamMapperMapper_(id<ComThoughtworksXstreamMapperMapper> mapper) {
  ComThoughtworksXstreamConvertersExtendedJavaClassConverter *self = [ComThoughtworksXstreamConvertersExtendedJavaClassConverter alloc];
  ComThoughtworksXstreamConvertersExtendedJavaClassConverter_initWithComThoughtworksXstreamMapperMapper_(self, mapper);
  return self;
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(ComThoughtworksXstreamConvertersExtendedJavaClassConverter)
