//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/Zetzsche/Development/SimarisCurves/com.thoughtworks.xstream/bin/src/com/thoughtworks/xstream/converters/extended/UseAttributeForEnumMapper.java
//

#ifndef _ComThoughtworksXstreamConvertersExtendedUseAttributeForEnumMapper_H_
#define _ComThoughtworksXstreamConvertersExtendedUseAttributeForEnumMapper_H_

#include "J2ObjC_header.h"
#include "com/thoughtworks/xstream/mapper/AttributeMapper.h"

@class IOSClass;
@protocol ComThoughtworksXstreamConvertersSingleValueConverter;
@protocol ComThoughtworksXstreamMapperMapper;

@interface ComThoughtworksXstreamConvertersExtendedUseAttributeForEnumMapper : ComThoughtworksXstreamMapperAttributeMapper

#pragma mark Public

- (instancetype)initWithComThoughtworksXstreamMapperMapper:(id<ComThoughtworksXstreamMapperMapper>)wrapped;

- (id<ComThoughtworksXstreamConvertersSingleValueConverter>)getConverterFromAttributeWithIOSClass:(IOSClass *)definedIn
                                                                                     withNSString:(NSString *)attribute
                                                                                     withIOSClass:(IOSClass *)type;

- (id<ComThoughtworksXstreamConvertersSingleValueConverter>)getConverterFromItemTypeWithNSString:(NSString *)fieldName
                                                                                    withIOSClass:(IOSClass *)type
                                                                                    withIOSClass:(IOSClass *)definedIn;

+ (jboolean)isEnumWithIOSClass:(IOSClass *)type;

- (jboolean)shouldLookForSingleValueConverterWithNSString:(NSString *)fieldName
                                             withIOSClass:(IOSClass *)type
                                             withIOSClass:(IOSClass *)definedIn;

#pragma mark Package-Private

+ (id<ComThoughtworksXstreamMapperMapper>)createEnumMapperWithComThoughtworksXstreamMapperMapper:(id<ComThoughtworksXstreamMapperMapper>)mapper;

@end

J2OBJC_EMPTY_STATIC_INIT(ComThoughtworksXstreamConvertersExtendedUseAttributeForEnumMapper)

FOUNDATION_EXPORT void ComThoughtworksXstreamConvertersExtendedUseAttributeForEnumMapper_initWithComThoughtworksXstreamMapperMapper_(ComThoughtworksXstreamConvertersExtendedUseAttributeForEnumMapper *self, id<ComThoughtworksXstreamMapperMapper> wrapped);

FOUNDATION_EXPORT ComThoughtworksXstreamConvertersExtendedUseAttributeForEnumMapper *new_ComThoughtworksXstreamConvertersExtendedUseAttributeForEnumMapper_initWithComThoughtworksXstreamMapperMapper_(id<ComThoughtworksXstreamMapperMapper> wrapped) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT jboolean ComThoughtworksXstreamConvertersExtendedUseAttributeForEnumMapper_isEnumWithIOSClass_(IOSClass *type);

FOUNDATION_EXPORT id<ComThoughtworksXstreamMapperMapper> ComThoughtworksXstreamConvertersExtendedUseAttributeForEnumMapper_createEnumMapperWithComThoughtworksXstreamMapperMapper_(id<ComThoughtworksXstreamMapperMapper> mapper);

J2OBJC_TYPE_LITERAL_HEADER(ComThoughtworksXstreamConvertersExtendedUseAttributeForEnumMapper)

#endif // _ComThoughtworksXstreamConvertersExtendedUseAttributeForEnumMapper_H_
