//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/Zetzsche/Development/SimarisCurves/com.thoughtworks.xstream/bin/src/com/thoughtworks/xstream/security/NullPermission.java
//

#ifndef _ComThoughtworksXstreamSecurityNullPermission_H_
#define _ComThoughtworksXstreamSecurityNullPermission_H_

#include "J2ObjC_header.h"
#include "com/thoughtworks/xstream/security/TypePermission.h"

@class IOSClass;

@interface ComThoughtworksXstreamSecurityNullPermission : NSObject < ComThoughtworksXstreamSecurityTypePermission >

#pragma mark Public

- (instancetype)init;

- (jboolean)allowsWithIOSClass:(IOSClass *)type;

@end

J2OBJC_STATIC_INIT(ComThoughtworksXstreamSecurityNullPermission)

FOUNDATION_EXPORT id<ComThoughtworksXstreamSecurityTypePermission> ComThoughtworksXstreamSecurityNullPermission_NULL__;
J2OBJC_STATIC_FIELD_GETTER(ComThoughtworksXstreamSecurityNullPermission, NULL__, id<ComThoughtworksXstreamSecurityTypePermission>)

FOUNDATION_EXPORT void ComThoughtworksXstreamSecurityNullPermission_init(ComThoughtworksXstreamSecurityNullPermission *self);

FOUNDATION_EXPORT ComThoughtworksXstreamSecurityNullPermission *new_ComThoughtworksXstreamSecurityNullPermission_init() NS_RETURNS_RETAINED;

J2OBJC_TYPE_LITERAL_HEADER(ComThoughtworksXstreamSecurityNullPermission)

#endif // _ComThoughtworksXstreamSecurityNullPermission_H_
