//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/Zetzsche/Development/SimarisCurves/com.thoughtworks.xstream/bin/src/com/thoughtworks/xstream/security/RegExpTypePermission.java
//

#ifndef _ComThoughtworksXstreamSecurityRegExpTypePermission_H_
#define _ComThoughtworksXstreamSecurityRegExpTypePermission_H_

#include "J2ObjC_header.h"
#include "com/thoughtworks/xstream/security/TypePermission.h"

@class IOSClass;
@class IOSObjectArray;

@interface ComThoughtworksXstreamSecurityRegExpTypePermission : NSObject < ComThoughtworksXstreamSecurityTypePermission >

#pragma mark Public

- (instancetype)initWithJavaUtilRegexPatternArray:(IOSObjectArray *)patterns;

- (instancetype)initWithNSStringArray:(IOSObjectArray *)patterns;

- (jboolean)allowsWithIOSClass:(IOSClass *)type;

@end

J2OBJC_EMPTY_STATIC_INIT(ComThoughtworksXstreamSecurityRegExpTypePermission)

FOUNDATION_EXPORT void ComThoughtworksXstreamSecurityRegExpTypePermission_initWithNSStringArray_(ComThoughtworksXstreamSecurityRegExpTypePermission *self, IOSObjectArray *patterns);

FOUNDATION_EXPORT ComThoughtworksXstreamSecurityRegExpTypePermission *new_ComThoughtworksXstreamSecurityRegExpTypePermission_initWithNSStringArray_(IOSObjectArray *patterns) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT void ComThoughtworksXstreamSecurityRegExpTypePermission_initWithJavaUtilRegexPatternArray_(ComThoughtworksXstreamSecurityRegExpTypePermission *self, IOSObjectArray *patterns);

FOUNDATION_EXPORT ComThoughtworksXstreamSecurityRegExpTypePermission *new_ComThoughtworksXstreamSecurityRegExpTypePermission_initWithJavaUtilRegexPatternArray_(IOSObjectArray *patterns) NS_RETURNS_RETAINED;

J2OBJC_TYPE_LITERAL_HEADER(ComThoughtworksXstreamSecurityRegExpTypePermission)

#endif // _ComThoughtworksXstreamSecurityRegExpTypePermission_H_
