//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/Zetzsche/Development/SimarisCurves/com.thoughtworks.xstream/src/com/thoughtworks/xstream/converters/reflection/AbstractReflectionConverter.java
//

#ifndef _ComThoughtworksXstreamConvertersReflectionAbstractReflectionConverter_H_
#define _ComThoughtworksXstreamConvertersReflectionAbstractReflectionConverter_H_

@class ComThoughtworksXstreamConvertersReflectionSerializationMethodInvoker;
@class IOSClass;
@class JavaLangReflectField;
@protocol ComThoughtworksXstreamConvertersMarshallingContext;
@protocol ComThoughtworksXstreamConvertersReflectionReflectionProvider;
@protocol ComThoughtworksXstreamConvertersUnmarshallingContext;
@protocol ComThoughtworksXstreamIoHierarchicalStreamReader;
@protocol ComThoughtworksXstreamIoHierarchicalStreamWriter;
@protocol ComThoughtworksXstreamMapperMapper;
@protocol JavaUtilList;
@protocol JavaUtilMap;
@protocol JavaUtilSet;

#import "JreEmulation.h"
#include "com/thoughtworks/xstream/converters/ConversionException.h"
#include "com/thoughtworks/xstream/converters/Converter.h"
#include "com/thoughtworks/xstream/converters/reflection/ReflectionProvider.h"
#include "com/thoughtworks/xstream/core/Caching.h"
#include "java/util/AbstractList.h"
#include "java/util/ArrayList.h"
#include "java/util/HashSet.h"

@interface ComThoughtworksXstreamConvertersReflectionAbstractReflectionConverter : NSObject < ComThoughtworksXstreamConvertersConverter, ComThoughtworksXstreamCoreCaching > {
 @public
  id<ComThoughtworksXstreamConvertersReflectionReflectionProvider> reflectionProvider_;
  id<ComThoughtworksXstreamMapperMapper> mapper_;
  ComThoughtworksXstreamConvertersReflectionSerializationMethodInvoker *serializationMethodInvoker_;
  id<ComThoughtworksXstreamConvertersReflectionReflectionProvider> pureJavaReflectionProvider_;
}

- (instancetype)initWithComThoughtworksXstreamMapperMapper:(id<ComThoughtworksXstreamMapperMapper>)mapper
withComThoughtworksXstreamConvertersReflectionReflectionProvider:(id<ComThoughtworksXstreamConvertersReflectionReflectionProvider>)reflectionProvider;

- (jboolean)canAccessWithIOSClass:(IOSClass *)type;

- (void)marshalWithId:(id)original
withComThoughtworksXstreamIoHierarchicalStreamWriter:(id<ComThoughtworksXstreamIoHierarchicalStreamWriter>)writer
withComThoughtworksXstreamConvertersMarshallingContext:(id<ComThoughtworksXstreamConvertersMarshallingContext>)context;

- (void)doMarshalWithId:(id)source
withComThoughtworksXstreamIoHierarchicalStreamWriter:(id<ComThoughtworksXstreamIoHierarchicalStreamWriter>)writer
withComThoughtworksXstreamConvertersMarshallingContext:(id<ComThoughtworksXstreamConvertersMarshallingContext>)context;

- (void)marshallFieldWithComThoughtworksXstreamConvertersMarshallingContext:(id<ComThoughtworksXstreamConvertersMarshallingContext>)context
                                                                     withId:(id)newObj
                                                   withJavaLangReflectField:(JavaLangReflectField *)field;

- (id)unmarshalWithComThoughtworksXstreamIoHierarchicalStreamReader:(id<ComThoughtworksXstreamIoHierarchicalStreamReader>)reader
           withComThoughtworksXstreamConvertersUnmarshallingContext:(id<ComThoughtworksXstreamConvertersUnmarshallingContext>)context;

- (id)doUnmarshalWithId:(id)result
withComThoughtworksXstreamIoHierarchicalStreamReader:(id<ComThoughtworksXstreamIoHierarchicalStreamReader>)reader
withComThoughtworksXstreamConvertersUnmarshallingContext:(id<ComThoughtworksXstreamConvertersUnmarshallingContext>)context;

- (id)unmarshallFieldWithComThoughtworksXstreamConvertersUnmarshallingContext:(id<ComThoughtworksXstreamConvertersUnmarshallingContext>)context
                                                                       withId:(id)result
                                                                 withIOSClass:(IOSClass *)type
                                                     withJavaLangReflectField:(JavaLangReflectField *)field;

- (jboolean)shouldUnmarshalTransientFields;

- (jboolean)shouldUnmarshalFieldWithJavaLangReflectField:(JavaLangReflectField *)field;

- (void)handleUnknownFieldWithIOSClass:(IOSClass *)classDefiningField
                          withNSString:(NSString *)fieldName
                          withIOSClass:(IOSClass *)resultType
                          withNSString:(NSString *)originalNodeName;

- (void)writeValueToImplicitCollectionWithId:(id)value
                             withJavaUtilMap:(id<JavaUtilMap>)implicitCollections
                                      withId:(id)result
                                withNSString:(NSString *)implicitFieldName;

- (IOSClass *)readDeclaringClassWithComThoughtworksXstreamIoHierarchicalStreamReader:(id<ComThoughtworksXstreamIoHierarchicalStreamReader>)reader;

- (id)instantiateNewInstanceWithComThoughtworksXstreamIoHierarchicalStreamReader:(id<ComThoughtworksXstreamIoHierarchicalStreamReader>)reader
                        withComThoughtworksXstreamConvertersUnmarshallingContext:(id<ComThoughtworksXstreamConvertersUnmarshallingContext>)context;

- (void)flushCache;

- (id)readResolve;

- (void)copyAllFieldsTo:(ComThoughtworksXstreamConvertersReflectionAbstractReflectionConverter *)other;

@end

__attribute__((always_inline)) inline void ComThoughtworksXstreamConvertersReflectionAbstractReflectionConverter_init() {}

J2OBJC_FIELD_SETTER(ComThoughtworksXstreamConvertersReflectionAbstractReflectionConverter, reflectionProvider_, id<ComThoughtworksXstreamConvertersReflectionReflectionProvider>)
J2OBJC_FIELD_SETTER(ComThoughtworksXstreamConvertersReflectionAbstractReflectionConverter, mapper_, id<ComThoughtworksXstreamMapperMapper>)
J2OBJC_FIELD_SETTER(ComThoughtworksXstreamConvertersReflectionAbstractReflectionConverter, serializationMethodInvoker_, ComThoughtworksXstreamConvertersReflectionSerializationMethodInvoker *)
J2OBJC_FIELD_SETTER(ComThoughtworksXstreamConvertersReflectionAbstractReflectionConverter, pureJavaReflectionProvider_, id<ComThoughtworksXstreamConvertersReflectionReflectionProvider>)

@interface ComThoughtworksXstreamConvertersReflectionAbstractReflectionConverter_DuplicateFieldException : ComThoughtworksXstreamConvertersConversionException {
}

- (instancetype)initWithNSString:(NSString *)msg;

@end

__attribute__((always_inline)) inline void ComThoughtworksXstreamConvertersReflectionAbstractReflectionConverter_DuplicateFieldException_init() {}

@interface ComThoughtworksXstreamConvertersReflectionAbstractReflectionConverter_UnknownFieldException : ComThoughtworksXstreamConvertersConversionException {
}

- (instancetype)initWithNSString:(NSString *)type
                    withNSString:(NSString *)field;

@end

__attribute__((always_inline)) inline void ComThoughtworksXstreamConvertersReflectionAbstractReflectionConverter_UnknownFieldException_init() {}

@interface ComThoughtworksXstreamConvertersReflectionAbstractReflectionConverter_FieldInfo : NSObject {
 @public
  NSString *fieldName_;
  IOSClass *type_;
  IOSClass *definedIn_;
  id value_;
}

- (instancetype)initWithNSString:(NSString *)fieldName
                    withIOSClass:(IOSClass *)type
                    withIOSClass:(IOSClass *)definedIn
                          withId:(id)value;

- (void)copyAllFieldsTo:(ComThoughtworksXstreamConvertersReflectionAbstractReflectionConverter_FieldInfo *)other;

@end

__attribute__((always_inline)) inline void ComThoughtworksXstreamConvertersReflectionAbstractReflectionConverter_FieldInfo_init() {}

J2OBJC_FIELD_SETTER(ComThoughtworksXstreamConvertersReflectionAbstractReflectionConverter_FieldInfo, fieldName_, NSString *)
J2OBJC_FIELD_SETTER(ComThoughtworksXstreamConvertersReflectionAbstractReflectionConverter_FieldInfo, type_, IOSClass *)
J2OBJC_FIELD_SETTER(ComThoughtworksXstreamConvertersReflectionAbstractReflectionConverter_FieldInfo, definedIn_, IOSClass *)
J2OBJC_FIELD_SETTER(ComThoughtworksXstreamConvertersReflectionAbstractReflectionConverter_FieldInfo, value_, id)

@interface ComThoughtworksXstreamConvertersReflectionAbstractReflectionConverter_ArraysList : JavaUtilArrayList {
 @public
  IOSClass *physicalFieldType_;
}

- (instancetype)initWithIOSClass:(IOSClass *)physicalFieldType;

- (id)toPhysicalArray;

- (void)copyAllFieldsTo:(ComThoughtworksXstreamConvertersReflectionAbstractReflectionConverter_ArraysList *)other;


@end

__attribute__((always_inline)) inline void ComThoughtworksXstreamConvertersReflectionAbstractReflectionConverter_ArraysList_init() {}

J2OBJC_FIELD_SETTER(ComThoughtworksXstreamConvertersReflectionAbstractReflectionConverter_ArraysList, physicalFieldType_, IOSClass *)

@interface ComThoughtworksXstreamConvertersReflectionAbstractReflectionConverter_MappingList : JavaUtilAbstractList {
 @public
  ComThoughtworksXstreamConvertersReflectionAbstractReflectionConverter *this$0_;
  id<JavaUtilMap> map_;
  NSString *keyFieldName_;
  id<JavaUtilMap> fieldCache_;
}

- (instancetype)initWithComThoughtworksXstreamConvertersReflectionAbstractReflectionConverter:(ComThoughtworksXstreamConvertersReflectionAbstractReflectionConverter *)outer$
                                                                              withJavaUtilMap:(id<JavaUtilMap>)map
                                                                                 withNSString:(NSString *)keyFieldName;

- (jboolean)addWithId:(id)object;

- (id)getWithInt:(jint)index;

- (jint)size;

- (void)copyAllFieldsTo:(ComThoughtworksXstreamConvertersReflectionAbstractReflectionConverter_MappingList *)other;


@end

__attribute__((always_inline)) inline void ComThoughtworksXstreamConvertersReflectionAbstractReflectionConverter_MappingList_init() {}

J2OBJC_FIELD_SETTER(ComThoughtworksXstreamConvertersReflectionAbstractReflectionConverter_MappingList, this$0_, ComThoughtworksXstreamConvertersReflectionAbstractReflectionConverter *)
J2OBJC_FIELD_SETTER(ComThoughtworksXstreamConvertersReflectionAbstractReflectionConverter_MappingList, map_, id<JavaUtilMap>)
J2OBJC_FIELD_SETTER(ComThoughtworksXstreamConvertersReflectionAbstractReflectionConverter_MappingList, keyFieldName_, NSString *)
J2OBJC_FIELD_SETTER(ComThoughtworksXstreamConvertersReflectionAbstractReflectionConverter_MappingList, fieldCache_, id<JavaUtilMap>)

@interface ComThoughtworksXstreamConvertersReflectionAbstractReflectionConverter_$1 : NSObject < ComThoughtworksXstreamConvertersReflectionReflectionProvider_Visitor > {
 @public
  ComThoughtworksXstreamConvertersReflectionAbstractReflectionConverter *this$0_;
  id<JavaUtilSet> writtenAttributes_;
  id<JavaUtilMap> val$defaultFieldDefinition_;
  id val$source_;
  id<ComThoughtworksXstreamIoHierarchicalStreamWriter> val$writer_;
  id<JavaUtilList> val$fields_;
}

- (void)visitWithNSString:(NSString *)fieldName
             withIOSClass:(IOSClass *)type
             withIOSClass:(IOSClass *)definedIn
                   withId:(id)value;

- (instancetype)initWithComThoughtworksXstreamConvertersReflectionAbstractReflectionConverter:(ComThoughtworksXstreamConvertersReflectionAbstractReflectionConverter *)outer$
                                                                              withJavaUtilMap:(id<JavaUtilMap>)capture$0
                                                                                       withId:(id)capture$1
                                         withComThoughtworksXstreamIoHierarchicalStreamWriter:(id<ComThoughtworksXstreamIoHierarchicalStreamWriter>)capture$2
                                                                             withJavaUtilList:(id<JavaUtilList>)capture$3;

- (void)copyAllFieldsTo:(ComThoughtworksXstreamConvertersReflectionAbstractReflectionConverter_$1 *)other;

@end

__attribute__((always_inline)) inline void ComThoughtworksXstreamConvertersReflectionAbstractReflectionConverter_$1_init() {}

J2OBJC_FIELD_SETTER(ComThoughtworksXstreamConvertersReflectionAbstractReflectionConverter_$1, this$0_, ComThoughtworksXstreamConvertersReflectionAbstractReflectionConverter *)
J2OBJC_FIELD_SETTER(ComThoughtworksXstreamConvertersReflectionAbstractReflectionConverter_$1, writtenAttributes_, id<JavaUtilSet>)
J2OBJC_FIELD_SETTER(ComThoughtworksXstreamConvertersReflectionAbstractReflectionConverter_$1, val$defaultFieldDefinition_, id<JavaUtilMap>)
J2OBJC_FIELD_SETTER(ComThoughtworksXstreamConvertersReflectionAbstractReflectionConverter_$1, val$source_, id)
J2OBJC_FIELD_SETTER(ComThoughtworksXstreamConvertersReflectionAbstractReflectionConverter_$1, val$writer_, id<ComThoughtworksXstreamIoHierarchicalStreamWriter>)
J2OBJC_FIELD_SETTER(ComThoughtworksXstreamConvertersReflectionAbstractReflectionConverter_$1, val$fields_, id<JavaUtilList>)

@interface ComThoughtworksXstreamConvertersReflectionAbstractReflectionConverter_$2 : NSObject {
 @public
  ComThoughtworksXstreamConvertersReflectionAbstractReflectionConverter *this$0_;
  id<JavaUtilList> val$fields_;
  id val$source_;
  id<ComThoughtworksXstreamConvertersMarshallingContext> val$context_;
  id<ComThoughtworksXstreamIoHierarchicalStreamWriter> val$writer_;
  id<JavaUtilMap> val$defaultFieldDefinition_;
}

- (void)writeFieldWithNSString:(NSString *)fieldName
                  withNSString:(NSString *)aliasName
                  withIOSClass:(IOSClass *)fieldType
                  withIOSClass:(IOSClass *)definedIn
                        withId:(id)newObj;

- (void)writeItemWithId:(id)item
withComThoughtworksXstreamConvertersMarshallingContext:(id<ComThoughtworksXstreamConvertersMarshallingContext>)context
withComThoughtworksXstreamIoHierarchicalStreamWriter:(id<ComThoughtworksXstreamIoHierarchicalStreamWriter>)writer;

- (instancetype)initWithComThoughtworksXstreamConvertersReflectionAbstractReflectionConverter:(ComThoughtworksXstreamConvertersReflectionAbstractReflectionConverter *)outer$
                                                                             withJavaUtilList:(id<JavaUtilList>)capture$0
                                                                                       withId:(id)capture$1
                                       withComThoughtworksXstreamConvertersMarshallingContext:(id<ComThoughtworksXstreamConvertersMarshallingContext>)capture$2
                                         withComThoughtworksXstreamIoHierarchicalStreamWriter:(id<ComThoughtworksXstreamIoHierarchicalStreamWriter>)capture$3
                                                                              withJavaUtilMap:(id<JavaUtilMap>)capture$4;

@end

__attribute__((always_inline)) inline void ComThoughtworksXstreamConvertersReflectionAbstractReflectionConverter_$2_init() {}

J2OBJC_FIELD_SETTER(ComThoughtworksXstreamConvertersReflectionAbstractReflectionConverter_$2, this$0_, ComThoughtworksXstreamConvertersReflectionAbstractReflectionConverter *)
J2OBJC_FIELD_SETTER(ComThoughtworksXstreamConvertersReflectionAbstractReflectionConverter_$2, val$fields_, id<JavaUtilList>)
J2OBJC_FIELD_SETTER(ComThoughtworksXstreamConvertersReflectionAbstractReflectionConverter_$2, val$source_, id)
J2OBJC_FIELD_SETTER(ComThoughtworksXstreamConvertersReflectionAbstractReflectionConverter_$2, val$context_, id<ComThoughtworksXstreamConvertersMarshallingContext>)
J2OBJC_FIELD_SETTER(ComThoughtworksXstreamConvertersReflectionAbstractReflectionConverter_$2, val$writer_, id<ComThoughtworksXstreamIoHierarchicalStreamWriter>)
J2OBJC_FIELD_SETTER(ComThoughtworksXstreamConvertersReflectionAbstractReflectionConverter_$2, val$defaultFieldDefinition_, id<JavaUtilMap>)

@interface ComThoughtworksXstreamConvertersReflectionAbstractReflectionConverter_$3 : JavaUtilHashSet {
}

- (jboolean)addWithId:(id)e;

- (instancetype)init;


@end

__attribute__((always_inline)) inline void ComThoughtworksXstreamConvertersReflectionAbstractReflectionConverter_$3_init() {}

#endif // _ComThoughtworksXstreamConvertersReflectionAbstractReflectionConverter_H_
