//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/Zetzsche/Development/SimarisCurves/com.thoughtworks.xstream/bin/src/com/thoughtworks/xstream/converters/reflection/AbstractReflectionConverter.java
//

#ifndef _ComThoughtworksXstreamConvertersReflectionAbstractReflectionConverter_H_
#define _ComThoughtworksXstreamConvertersReflectionAbstractReflectionConverter_H_

#include "J2ObjC_header.h"
#include "com/thoughtworks/xstream/converters/ConversionException.h"
#include "com/thoughtworks/xstream/converters/Converter.h"
#include "com/thoughtworks/xstream/core/Caching.h"

@class ComThoughtworksXstreamConvertersReflectionSerializationMethodInvoker;
@class IOSClass;
@class JavaLangReflectField;
@protocol ComThoughtworksXstreamConvertersMarshallingContext;
@protocol ComThoughtworksXstreamConvertersReflectionReflectionProvider;
@protocol ComThoughtworksXstreamConvertersUnmarshallingContext;
@protocol ComThoughtworksXstreamIoHierarchicalStreamReader;
@protocol ComThoughtworksXstreamIoHierarchicalStreamWriter;
@protocol ComThoughtworksXstreamMapperMapper;

@interface ComThoughtworksXstreamConvertersReflectionAbstractReflectionConverter : NSObject < ComThoughtworksXstreamConvertersConverter, ComThoughtworksXstreamCoreCaching > {
 @public
  id<ComThoughtworksXstreamConvertersReflectionReflectionProvider> reflectionProvider_;
  id<ComThoughtworksXstreamMapperMapper> mapper_;
  ComThoughtworksXstreamConvertersReflectionSerializationMethodInvoker *serializationMethodInvoker_;
}

#pragma mark Public

- (instancetype)initWithComThoughtworksXstreamMapperMapper:(id<ComThoughtworksXstreamMapperMapper>)mapper
withComThoughtworksXstreamConvertersReflectionReflectionProvider:(id<ComThoughtworksXstreamConvertersReflectionReflectionProvider>)reflectionProvider;

- (id)doUnmarshalWithId:(id)result
withComThoughtworksXstreamIoHierarchicalStreamReader:(id<ComThoughtworksXstreamIoHierarchicalStreamReader>)reader
withComThoughtworksXstreamConvertersUnmarshallingContext:(id<ComThoughtworksXstreamConvertersUnmarshallingContext>)context;

- (void)flushCache;

- (void)marshalWithId:(id)original
withComThoughtworksXstreamIoHierarchicalStreamWriter:(id<ComThoughtworksXstreamIoHierarchicalStreamWriter>)writer
withComThoughtworksXstreamConvertersMarshallingContext:(id<ComThoughtworksXstreamConvertersMarshallingContext>)context;

- (id)unmarshalWithComThoughtworksXstreamIoHierarchicalStreamReader:(id<ComThoughtworksXstreamIoHierarchicalStreamReader>)reader
           withComThoughtworksXstreamConvertersUnmarshallingContext:(id<ComThoughtworksXstreamConvertersUnmarshallingContext>)context;

#pragma mark Protected

- (jboolean)canAccessWithIOSClass:(IOSClass *)type;

- (void)doMarshalWithId:(id)source
withComThoughtworksXstreamIoHierarchicalStreamWriter:(id<ComThoughtworksXstreamIoHierarchicalStreamWriter>)writer
withComThoughtworksXstreamConvertersMarshallingContext:(id<ComThoughtworksXstreamConvertersMarshallingContext>)context;

- (id)instantiateNewInstanceWithComThoughtworksXstreamIoHierarchicalStreamReader:(id<ComThoughtworksXstreamIoHierarchicalStreamReader>)reader
                        withComThoughtworksXstreamConvertersUnmarshallingContext:(id<ComThoughtworksXstreamConvertersUnmarshallingContext>)context;

- (void)marshallFieldWithComThoughtworksXstreamConvertersMarshallingContext:(id<ComThoughtworksXstreamConvertersMarshallingContext>)context
                                                                     withId:(id)newObj
                                                   withJavaLangReflectField:(JavaLangReflectField *)field;

- (jboolean)shouldUnmarshalFieldWithJavaLangReflectField:(JavaLangReflectField *)field;

- (jboolean)shouldUnmarshalTransientFields;

- (id)unmarshallFieldWithComThoughtworksXstreamConvertersUnmarshallingContext:(id<ComThoughtworksXstreamConvertersUnmarshallingContext>)context
                                                                       withId:(id)result
                                                                 withIOSClass:(IOSClass *)type
                                                     withJavaLangReflectField:(JavaLangReflectField *)field;

@end

J2OBJC_EMPTY_STATIC_INIT(ComThoughtworksXstreamConvertersReflectionAbstractReflectionConverter)

J2OBJC_FIELD_SETTER(ComThoughtworksXstreamConvertersReflectionAbstractReflectionConverter, reflectionProvider_, id<ComThoughtworksXstreamConvertersReflectionReflectionProvider>)
J2OBJC_FIELD_SETTER(ComThoughtworksXstreamConvertersReflectionAbstractReflectionConverter, mapper_, id<ComThoughtworksXstreamMapperMapper>)
J2OBJC_FIELD_SETTER(ComThoughtworksXstreamConvertersReflectionAbstractReflectionConverter, serializationMethodInvoker_, ComThoughtworksXstreamConvertersReflectionSerializationMethodInvoker *)

FOUNDATION_EXPORT void ComThoughtworksXstreamConvertersReflectionAbstractReflectionConverter_initWithComThoughtworksXstreamMapperMapper_withComThoughtworksXstreamConvertersReflectionReflectionProvider_(ComThoughtworksXstreamConvertersReflectionAbstractReflectionConverter *self, id<ComThoughtworksXstreamMapperMapper> mapper, id<ComThoughtworksXstreamConvertersReflectionReflectionProvider> reflectionProvider);

J2OBJC_TYPE_LITERAL_HEADER(ComThoughtworksXstreamConvertersReflectionAbstractReflectionConverter)

@interface ComThoughtworksXstreamConvertersReflectionAbstractReflectionConverter_DuplicateFieldException : ComThoughtworksXstreamConvertersConversionException

#pragma mark Public

- (instancetype)initWithNSString:(NSString *)msg;

@end

J2OBJC_EMPTY_STATIC_INIT(ComThoughtworksXstreamConvertersReflectionAbstractReflectionConverter_DuplicateFieldException)

FOUNDATION_EXPORT void ComThoughtworksXstreamConvertersReflectionAbstractReflectionConverter_DuplicateFieldException_initWithNSString_(ComThoughtworksXstreamConvertersReflectionAbstractReflectionConverter_DuplicateFieldException *self, NSString *msg);

FOUNDATION_EXPORT ComThoughtworksXstreamConvertersReflectionAbstractReflectionConverter_DuplicateFieldException *new_ComThoughtworksXstreamConvertersReflectionAbstractReflectionConverter_DuplicateFieldException_initWithNSString_(NSString *msg) NS_RETURNS_RETAINED;

J2OBJC_TYPE_LITERAL_HEADER(ComThoughtworksXstreamConvertersReflectionAbstractReflectionConverter_DuplicateFieldException)

@interface ComThoughtworksXstreamConvertersReflectionAbstractReflectionConverter_UnknownFieldException : ComThoughtworksXstreamConvertersConversionException

#pragma mark Public

- (instancetype)initWithNSString:(NSString *)type
                    withNSString:(NSString *)field;

@end

J2OBJC_EMPTY_STATIC_INIT(ComThoughtworksXstreamConvertersReflectionAbstractReflectionConverter_UnknownFieldException)

FOUNDATION_EXPORT void ComThoughtworksXstreamConvertersReflectionAbstractReflectionConverter_UnknownFieldException_initWithNSString_withNSString_(ComThoughtworksXstreamConvertersReflectionAbstractReflectionConverter_UnknownFieldException *self, NSString *type, NSString *field);

FOUNDATION_EXPORT ComThoughtworksXstreamConvertersReflectionAbstractReflectionConverter_UnknownFieldException *new_ComThoughtworksXstreamConvertersReflectionAbstractReflectionConverter_UnknownFieldException_initWithNSString_withNSString_(NSString *type, NSString *field) NS_RETURNS_RETAINED;

J2OBJC_TYPE_LITERAL_HEADER(ComThoughtworksXstreamConvertersReflectionAbstractReflectionConverter_UnknownFieldException)

#endif // _ComThoughtworksXstreamConvertersReflectionAbstractReflectionConverter_H_
