//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/Zetzsche/Development/SimarisCurves/com.thoughtworks.xstream/src/com/thoughtworks/xstream/converters/reflection/FieldDictionary.java
//

#ifndef _ComThoughtworksXstreamConvertersReflectionFieldDictionary_H_
#define _ComThoughtworksXstreamConvertersReflectionFieldDictionary_H_

@class IOSClass;
@class JavaLangReflectField;
@protocol ComThoughtworksXstreamConvertersReflectionFieldKeySorter;
@protocol JavaUtilIterator;
@protocol JavaUtilMap;

#import "JreEmulation.h"
#include "com/thoughtworks/xstream/core/Caching.h"

@interface ComThoughtworksXstreamConvertersReflectionFieldDictionary : NSObject < ComThoughtworksXstreamCoreCaching > {
 @public
  id<JavaUtilMap> keyedByFieldNameCache_;
  id<JavaUtilMap> keyedByFieldKeyCache_;
  id<ComThoughtworksXstreamConvertersReflectionFieldKeySorter> sorter_;
}

- (instancetype)init;

- (instancetype)initWithComThoughtworksXstreamConvertersReflectionFieldKeySorter:(id<ComThoughtworksXstreamConvertersReflectionFieldKeySorter>)sorter;

- (void)init__ OBJC_METHOD_FAMILY_NONE;

- (id<JavaUtilIterator>)serializableFieldsForWithIOSClass:(IOSClass *)cls;

- (id<JavaUtilIterator>)fieldsForWithIOSClass:(IOSClass *)cls;

- (JavaLangReflectField *)fieldWithIOSClass:(IOSClass *)cls
                               withNSString:(NSString *)name
                               withIOSClass:(IOSClass *)definedIn;

- (JavaLangReflectField *)fieldOrNullWithIOSClass:(IOSClass *)cls
                                     withNSString:(NSString *)name
                                     withIOSClass:(IOSClass *)definedIn;

- (id<JavaUtilMap>)buildMapWithIOSClass:(IOSClass *)type
                            withBoolean:(jboolean)tupleKeyed;

- (void)flushCache;

- (id)readResolve;

- (void)copyAllFieldsTo:(ComThoughtworksXstreamConvertersReflectionFieldDictionary *)other;

@end

__attribute__((always_inline)) inline void ComThoughtworksXstreamConvertersReflectionFieldDictionary_init() {}

J2OBJC_FIELD_SETTER(ComThoughtworksXstreamConvertersReflectionFieldDictionary, keyedByFieldNameCache_, id<JavaUtilMap>)
J2OBJC_FIELD_SETTER(ComThoughtworksXstreamConvertersReflectionFieldDictionary, keyedByFieldKeyCache_, id<JavaUtilMap>)
J2OBJC_FIELD_SETTER(ComThoughtworksXstreamConvertersReflectionFieldDictionary, sorter_, id<ComThoughtworksXstreamConvertersReflectionFieldKeySorter>)

#endif // _ComThoughtworksXstreamConvertersReflectionFieldDictionary_H_
