//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/Zetzsche/Development/SimarisCurves/com.thoughtworks.xstream/src/com/thoughtworks/xstream/converters/reflection/ImmutableFieldKeySorter.java
//

#line 1 "/Users/Zetzsche/Development/SimarisCurves/com.thoughtworks.xstream/src/com/thoughtworks/xstream/converters/reflection/ImmutableFieldKeySorter.java"

#include "IOSClass.h"
#include "com/thoughtworks/xstream/converters/reflection/ImmutableFieldKeySorter.h"
#include "java/util/Map.h"


#line 21
@implementation ComThoughtworksXstreamConvertersReflectionImmutableFieldKeySorter

- (id<JavaUtilMap>)sortWithIOSClass:(IOSClass *)type
                    withJavaUtilMap:(id<JavaUtilMap>)keyedByFieldKey {
  
#line 24
  return keyedByFieldKey;
}

- (instancetype)init {
  return [super init];
}

+ (const J2ObjcClassInfo *)__metadata {
  static const J2ObjcMethodInfo methods[] = {
    { "sortWithIOSClass:withJavaUtilMap:", "sort", "Ljava.util.Map;", 0x1, NULL },
    { "init", NULL, NULL, 0x1, NULL },
  };
  static const J2ObjcClassInfo _ComThoughtworksXstreamConvertersReflectionImmutableFieldKeySorter = { "ImmutableFieldKeySorter", "com.thoughtworks.xstream.converters.reflection", NULL, 0x1, 2, methods, 0, NULL, 0, NULL};
  return &_ComThoughtworksXstreamConvertersReflectionImmutableFieldKeySorter;
}

@end
