//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/Zetzsche/Development/SimarisCurves/com.thoughtworks.xstream/src/com/thoughtworks/xstream/converters/reflection/SelfStreamingInstanceChecker.java
//

#ifndef _ComThoughtworksXstreamConvertersReflectionSelfStreamingInstanceChecker_H_
#define _ComThoughtworksXstreamConvertersReflectionSelfStreamingInstanceChecker_H_

@protocol ComThoughtworksXstreamConvertersConverter;

#import "JreEmulation.h"
#include "com/thoughtworks/xstream/core/util/SelfStreamingInstanceChecker.h"

@interface ComThoughtworksXstreamConvertersReflectionSelfStreamingInstanceChecker : ComThoughtworksXstreamCoreUtilSelfStreamingInstanceChecker {
}

- (instancetype)initWithComThoughtworksXstreamConvertersConverter:(id<ComThoughtworksXstreamConvertersConverter>)defaultConverter
                                                           withId:(id)xstream;

@end

__attribute__((always_inline)) inline void ComThoughtworksXstreamConvertersReflectionSelfStreamingInstanceChecker_init() {}

#endif // _ComThoughtworksXstreamConvertersReflectionSelfStreamingInstanceChecker_H_
