//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/Zetzsche/Development/SimarisCurves/com.thoughtworks.xstream/bin/src/com/thoughtworks/xstream/converters/reflection/SerializationMethodInvoker.java
//

#ifndef _ComThoughtworksXstreamConvertersReflectionSerializationMethodInvoker_H_
#define _ComThoughtworksXstreamConvertersReflectionSerializationMethodInvoker_H_

#include "J2ObjC_header.h"
#include "com/thoughtworks/xstream/core/Caching.h"

@class IOSClass;
@class JavaIoObjectInputStream;
@class JavaIoObjectOutputStream;

@interface ComThoughtworksXstreamConvertersReflectionSerializationMethodInvoker : NSObject < ComThoughtworksXstreamCoreCaching >

#pragma mark Public

- (instancetype)init;

- (void)callReadObjectWithIOSClass:(IOSClass *)type
                            withId:(id)object
       withJavaIoObjectInputStream:(JavaIoObjectInputStream *)stream;

- (id)callReadResolveWithId:(id)result;

- (void)callWriteObjectWithIOSClass:(IOSClass *)type
                             withId:(id)instance
       withJavaIoObjectOutputStream:(JavaIoObjectOutputStream *)stream;

- (id)callWriteReplaceWithId:(id)object;

- (void)flushCache;

- (jboolean)supportsReadObjectWithIOSClass:(IOSClass *)type
                               withBoolean:(jboolean)includeBaseClasses;

- (jboolean)supportsWriteObjectWithIOSClass:(IOSClass *)type
                                withBoolean:(jboolean)includeBaseClasses;

@end

J2OBJC_STATIC_INIT(ComThoughtworksXstreamConvertersReflectionSerializationMethodInvoker)

FOUNDATION_EXPORT void ComThoughtworksXstreamConvertersReflectionSerializationMethodInvoker_init(ComThoughtworksXstreamConvertersReflectionSerializationMethodInvoker *self);

FOUNDATION_EXPORT ComThoughtworksXstreamConvertersReflectionSerializationMethodInvoker *new_ComThoughtworksXstreamConvertersReflectionSerializationMethodInvoker_init() NS_RETURNS_RETAINED;

J2OBJC_TYPE_LITERAL_HEADER(ComThoughtworksXstreamConvertersReflectionSerializationMethodInvoker)

#endif // _ComThoughtworksXstreamConvertersReflectionSerializationMethodInvoker_H_
