//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/Zetzsche/Development/SimarisCurves/com.thoughtworks.xstream/src/com/thoughtworks/xstream/core/DefaultConverterLookup.java
//

#ifndef _ComThoughtworksXstreamCoreDefaultConverterLookup_H_
#define _ComThoughtworksXstreamCoreDefaultConverterLookup_H_

@class ComThoughtworksXstreamCoreUtilPrioritizedList;
@class IOSClass;
@protocol ComThoughtworksXstreamConvertersConverter;
@protocol ComThoughtworksXstreamMapperMapper;
@protocol JavaUtilMap;

#import "JreEmulation.h"
#include "com/thoughtworks/xstream/converters/ConverterLookup.h"
#include "com/thoughtworks/xstream/converters/ConverterRegistry.h"
#include "com/thoughtworks/xstream/core/Caching.h"

@interface ComThoughtworksXstreamCoreDefaultConverterLookup : NSObject < ComThoughtworksXstreamConvertersConverterLookup, ComThoughtworksXstreamConvertersConverterRegistry, ComThoughtworksXstreamCoreCaching > {
 @public
  ComThoughtworksXstreamCoreUtilPrioritizedList *converters_;
  id<JavaUtilMap> typeToConverterMap_;
}

- (instancetype)init;

- (instancetype)initWithComThoughtworksXstreamMapperMapper:(id<ComThoughtworksXstreamMapperMapper>)mapper;

- (id<ComThoughtworksXstreamConvertersConverter>)lookupConverterForTypeWithIOSClass:(IOSClass *)type;

- (void)registerConverterWithComThoughtworksXstreamConvertersConverter:(id<ComThoughtworksXstreamConvertersConverter>)converter
                                                               withInt:(jint)priority;

- (void)flushCache;

- (id)readResolve;

- (void)copyAllFieldsTo:(ComThoughtworksXstreamCoreDefaultConverterLookup *)other;

@end

__attribute__((always_inline)) inline void ComThoughtworksXstreamCoreDefaultConverterLookup_init() {}

J2OBJC_FIELD_SETTER(ComThoughtworksXstreamCoreDefaultConverterLookup, converters_, ComThoughtworksXstreamCoreUtilPrioritizedList *)
J2OBJC_FIELD_SETTER(ComThoughtworksXstreamCoreDefaultConverterLookup, typeToConverterMap_, id<JavaUtilMap>)

#endif // _ComThoughtworksXstreamCoreDefaultConverterLookup_H_
