//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/Zetzsche/Development/SimarisCurves/com.thoughtworks.xstream/src/com/thoughtworks/xstream/core/MapBackedDataHolder.java
//

#line 1 "/Users/Zetzsche/Development/SimarisCurves/com.thoughtworks.xstream/src/com/thoughtworks/xstream/core/MapBackedDataHolder.java"

#include "com/thoughtworks/xstream/core/MapBackedDataHolder.h"
#include "java/util/Collection.h"
#include "java/util/Collections.h"
#include "java/util/HashMap.h"
#include "java/util/Iterator.h"
#include "java/util/Map.h"
#include "java/util/Set.h"


#line 21
@implementation ComThoughtworksXstreamCoreMapBackedDataHolder


#line 24
- (instancetype)init {
  return
#line 25
  [self initComThoughtworksXstreamCoreMapBackedDataHolderWithJavaUtilMap:[[JavaUtilHashMap alloc] init]];
}


#line 28
- (instancetype)initComThoughtworksXstreamCoreMapBackedDataHolderWithJavaUtilMap:(id<JavaUtilMap>)map {
  if (self = [super init]) {
    self->map_ = map;
  }
  return self;
}

- (instancetype)initWithJavaUtilMap:(id<JavaUtilMap>)map {
  return [self initComThoughtworksXstreamCoreMapBackedDataHolderWithJavaUtilMap:
#line 28
map];
}


#line 32
- (id)getWithId:(id)key {
  
#line 33
  return [((id<JavaUtilMap>) nil_chk(map_)) getWithId:key];
}


#line 36
- (void)putWithId:(id)key
           withId:(id)value {
  
#line 37
  (void) [((id<JavaUtilMap>) nil_chk(map_)) putWithId:key withId:value];
}


#line 40
- (id<JavaUtilIterator>)keys {
  
#line 41
  return [((id<JavaUtilCollection>) nil_chk([JavaUtilCollections unmodifiableCollectionWithJavaUtilCollection:[((id<JavaUtilMap>) nil_chk(map_)) keySet]])) iterator];
}

- (void)copyAllFieldsTo:(ComThoughtworksXstreamCoreMapBackedDataHolder *)other {
  [super copyAllFieldsTo:other];
  other->map_ = map_;
}

+ (const J2ObjcClassInfo *)__metadata {
  static const J2ObjcMethodInfo methods[] = {
    { "init", "MapBackedDataHolder", NULL, 0x1, NULL },
    { "initWithJavaUtilMap:", "MapBackedDataHolder", NULL, 0x1, NULL },
    { "getWithId:", "get", "Ljava.lang.Object;", 0x1, NULL },
    { "putWithId:withId:", "put", "V", 0x1, NULL },
    { "keys", NULL, "Ljava.util.Iterator;", 0x1, NULL },
  };
  static const J2ObjcFieldInfo fields[] = {
    { "map_", NULL, 0x12, "Ljava.util.Map;", NULL,  },
  };
  static const J2ObjcClassInfo _ComThoughtworksXstreamCoreMapBackedDataHolder = { "MapBackedDataHolder", "com.thoughtworks.xstream.core", NULL, 0x1, 5, methods, 1, fields, 0, NULL};
  return &_ComThoughtworksXstreamCoreMapBackedDataHolder;
}

@end
