//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/Zetzsche/Development/SimarisCurves/com.thoughtworks.xstream/src/com/thoughtworks/xstream/core/ReferenceByXPathMarshaller.java
//

#ifndef _ComThoughtworksXstreamCoreReferenceByXPathMarshaller_H_
#define _ComThoughtworksXstreamCoreReferenceByXPathMarshaller_H_

@class ComThoughtworksXstreamIoPathPath;
@protocol ComThoughtworksXstreamConvertersConverterLookup;
@protocol ComThoughtworksXstreamIoHierarchicalStreamWriter;
@protocol ComThoughtworksXstreamMapperMapper;

#import "JreEmulation.h"
#include "com/thoughtworks/xstream/core/AbstractReferenceMarshaller.h"

@interface ComThoughtworksXstreamCoreReferenceByXPathMarshaller : ComThoughtworksXstreamCoreAbstractReferenceMarshaller {
 @public
  jint mode_;
}

- (instancetype)initWithComThoughtworksXstreamIoHierarchicalStreamWriter:(id<ComThoughtworksXstreamIoHierarchicalStreamWriter>)writer
                     withComThoughtworksXstreamConvertersConverterLookup:(id<ComThoughtworksXstreamConvertersConverterLookup>)converterLookup
                                  withComThoughtworksXstreamMapperMapper:(id<ComThoughtworksXstreamMapperMapper>)mapper
                                                                 withInt:(jint)mode;

- (NSString *)createReferenceWithComThoughtworksXstreamIoPathPath:(ComThoughtworksXstreamIoPathPath *)currentPath
                                                           withId:(id)existingReferenceKey;

- (id)createReferenceKeyWithComThoughtworksXstreamIoPathPath:(ComThoughtworksXstreamIoPathPath *)currentPath
                                                      withId:(id)item;

- (void)fireValidReferenceWithId:(id)referenceKey;

- (void)copyAllFieldsTo:(ComThoughtworksXstreamCoreReferenceByXPathMarshaller *)other;

@end

__attribute__((always_inline)) inline void ComThoughtworksXstreamCoreReferenceByXPathMarshaller_init() {}

#endif // _ComThoughtworksXstreamCoreReferenceByXPathMarshaller_H_
