//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/Zetzsche/Development/SimarisCurves/com.thoughtworks.xstream/bin/src/com/thoughtworks/xstream/core/ReferenceByXPathMarshallingStrategy.java
//


#line 1 "/Users/Zetzsche/Development/SimarisCurves/com.thoughtworks.xstream/bin/src/com/thoughtworks/xstream/core/ReferenceByXPathMarshallingStrategy.java"

#include "J2ObjC_source.h"
#include "com/thoughtworks/xstream/converters/ConverterLookup.h"
#include "com/thoughtworks/xstream/core/AbstractTreeMarshallingStrategy.h"
#include "com/thoughtworks/xstream/core/ReferenceByXPathMarshaller.h"
#include "com/thoughtworks/xstream/core/ReferenceByXPathMarshallingStrategy.h"
#include "com/thoughtworks/xstream/core/ReferenceByXPathUnmarshaller.h"
#include "com/thoughtworks/xstream/core/TreeMarshaller.h"
#include "com/thoughtworks/xstream/core/TreeUnmarshaller.h"
#include "com/thoughtworks/xstream/io/HierarchicalStreamReader.h"
#include "com/thoughtworks/xstream/io/HierarchicalStreamWriter.h"
#include "com/thoughtworks/xstream/mapper/Mapper.h"

@interface ComThoughtworksXstreamCoreReferenceByXPathMarshallingStrategy () {
 @public
  jint mode_;
}

@end

jint ComThoughtworksXstreamCoreReferenceByXPathMarshallingStrategy_RELATIVE_ = 
#line 21
0;
jint ComThoughtworksXstreamCoreReferenceByXPathMarshallingStrategy_ABSOLUTE_ = 
#line 22
1;
jint ComThoughtworksXstreamCoreReferenceByXPathMarshallingStrategy_SINGLE_NODE_ = 
#line 23
2;


#line 19
@implementation ComThoughtworksXstreamCoreReferenceByXPathMarshallingStrategy


#line 26
- (instancetype)initWithInt:(jint)mode {
  ComThoughtworksXstreamCoreReferenceByXPathMarshallingStrategy_initWithInt_(self, mode);
  return self;
}


#line 30
- (ComThoughtworksXstreamCoreTreeUnmarshaller *)createUnmarshallingContextWithId:(id)root
                            withComThoughtworksXstreamIoHierarchicalStreamReader:(id<ComThoughtworksXstreamIoHierarchicalStreamReader>)reader
                             withComThoughtworksXstreamConvertersConverterLookup:(id<ComThoughtworksXstreamConvertersConverterLookup>)converterLookup
                                          withComThoughtworksXstreamMapperMapper:(id<ComThoughtworksXstreamMapperMapper>)mapper {
  
#line 32
  return new_ComThoughtworksXstreamCoreReferenceByXPathUnmarshaller_initWithId_withComThoughtworksXstreamIoHierarchicalStreamReader_withComThoughtworksXstreamConvertersConverterLookup_withComThoughtworksXstreamMapperMapper_(root, reader, converterLookup, mapper);
}


#line 35
- (ComThoughtworksXstreamCoreTreeMarshaller *)createMarshallingContextWithComThoughtworksXstreamIoHierarchicalStreamWriter:(id<ComThoughtworksXstreamIoHierarchicalStreamWriter>)writer
                                                                       withComThoughtworksXstreamConvertersConverterLookup:(id<ComThoughtworksXstreamConvertersConverterLookup>)converterLookup
                                                                                    withComThoughtworksXstreamMapperMapper:(id<ComThoughtworksXstreamMapperMapper>)mapper {
  
#line 37
  return new_ComThoughtworksXstreamCoreReferenceByXPathMarshaller_initWithComThoughtworksXstreamIoHierarchicalStreamWriter_withComThoughtworksXstreamConvertersConverterLookup_withComThoughtworksXstreamMapperMapper_withInt_(writer, converterLookup, mapper, mode_);
}

+ (const J2ObjcClassInfo *)__metadata {
  static const J2ObjcMethodInfo methods[] = {
    { "initWithInt:", "ReferenceByXPathMarshallingStrategy", NULL, 0x1, NULL, NULL },
    { "createUnmarshallingContextWithId:withComThoughtworksXstreamIoHierarchicalStreamReader:withComThoughtworksXstreamConvertersConverterLookup:withComThoughtworksXstreamMapperMapper:", "createUnmarshallingContext", "Lcom.thoughtworks.xstream.core.TreeUnmarshaller;", 0x4, NULL, NULL },
    { "createMarshallingContextWithComThoughtworksXstreamIoHierarchicalStreamWriter:withComThoughtworksXstreamConvertersConverterLookup:withComThoughtworksXstreamMapperMapper:", "createMarshallingContext", "Lcom.thoughtworks.xstream.core.TreeMarshaller;", 0x4, NULL, NULL },
  };
  static const J2ObjcFieldInfo fields[] = {
    { "RELATIVE_", NULL, 0x9, "I", &ComThoughtworksXstreamCoreReferenceByXPathMarshallingStrategy_RELATIVE_, NULL,  },
    { "ABSOLUTE_", NULL, 0x9, "I", &ComThoughtworksXstreamCoreReferenceByXPathMarshallingStrategy_ABSOLUTE_, NULL,  },
    { "SINGLE_NODE_", NULL, 0x9, "I", &ComThoughtworksXstreamCoreReferenceByXPathMarshallingStrategy_SINGLE_NODE_, NULL,  },
    { "mode_", NULL, 0x12, "I", NULL, NULL,  },
  };
  static const J2ObjcClassInfo _ComThoughtworksXstreamCoreReferenceByXPathMarshallingStrategy = { 2, "ReferenceByXPathMarshallingStrategy", "com.thoughtworks.xstream.core", NULL, 0x1, 3, methods, 4, fields, 0, NULL, 0, NULL, NULL, NULL };
  return &_ComThoughtworksXstreamCoreReferenceByXPathMarshallingStrategy;
}

@end


#line 26
void ComThoughtworksXstreamCoreReferenceByXPathMarshallingStrategy_initWithInt_(ComThoughtworksXstreamCoreReferenceByXPathMarshallingStrategy *self, jint mode) {
  (void) ComThoughtworksXstreamCoreAbstractTreeMarshallingStrategy_init(self);
  
#line 27
  self->mode_ = mode;
}


#line 26
ComThoughtworksXstreamCoreReferenceByXPathMarshallingStrategy *new_ComThoughtworksXstreamCoreReferenceByXPathMarshallingStrategy_initWithInt_(jint mode) {
  ComThoughtworksXstreamCoreReferenceByXPathMarshallingStrategy *self = [ComThoughtworksXstreamCoreReferenceByXPathMarshallingStrategy alloc];
  ComThoughtworksXstreamCoreReferenceByXPathMarshallingStrategy_initWithInt_(self, mode);
  return self;
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(ComThoughtworksXstreamCoreReferenceByXPathMarshallingStrategy)
