//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/Zetzsche/Development/SimarisCurves/com.thoughtworks.xstream/src/com/thoughtworks/xstream/converters/collections/PropertiesConverter.java
//

#ifndef _ComThoughtworksXstreamConvertersCollectionsPropertiesConverter_H_
#define _ComThoughtworksXstreamConvertersCollectionsPropertiesConverter_H_

@class IOSClass;
@class JavaLangReflectField;
@protocol ComThoughtworksXstreamConvertersMarshallingContext;
@protocol ComThoughtworksXstreamConvertersUnmarshallingContext;
@protocol ComThoughtworksXstreamIoHierarchicalStreamReader;
@protocol ComThoughtworksXstreamIoHierarchicalStreamWriter;

#import "JreEmulation.h"
#include "com/thoughtworks/xstream/converters/Converter.h"

@interface ComThoughtworksXstreamConvertersCollectionsPropertiesConverter : NSObject < ComThoughtworksXstreamConvertersConverter > {
 @public
  jboolean sort_;
}

- (instancetype)init;

- (instancetype)initWithBoolean:(jboolean)sort;

- (jboolean)canConvertWithIOSClass:(IOSClass *)type;

- (void)marshalWithId:(id)source
withComThoughtworksXstreamIoHierarchicalStreamWriter:(id<ComThoughtworksXstreamIoHierarchicalStreamWriter>)writer
withComThoughtworksXstreamConvertersMarshallingContext:(id<ComThoughtworksXstreamConvertersMarshallingContext>)context;

- (id)unmarshalWithComThoughtworksXstreamIoHierarchicalStreamReader:(id<ComThoughtworksXstreamIoHierarchicalStreamReader>)reader
           withComThoughtworksXstreamConvertersUnmarshallingContext:(id<ComThoughtworksXstreamConvertersUnmarshallingContext>)context;

- (void)copyAllFieldsTo:(ComThoughtworksXstreamConvertersCollectionsPropertiesConverter *)other;

@end

FOUNDATION_EXPORT BOOL ComThoughtworksXstreamConvertersCollectionsPropertiesConverter_initialized;
J2OBJC_STATIC_INIT(ComThoughtworksXstreamConvertersCollectionsPropertiesConverter)

FOUNDATION_EXPORT JavaLangReflectField *ComThoughtworksXstreamConvertersCollectionsPropertiesConverter_defaultsField_;
J2OBJC_STATIC_FIELD_GETTER(ComThoughtworksXstreamConvertersCollectionsPropertiesConverter, defaultsField_, JavaLangReflectField *)

#endif // _ComThoughtworksXstreamConvertersCollectionsPropertiesConverter_H_
