//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/Zetzsche/Development/SimarisCurves/com.thoughtworks.xstream/src/com/thoughtworks/xstream/io/AbstractWriter.java
//

#ifndef _ComThoughtworksXstreamIoAbstractWriter_H_
#define _ComThoughtworksXstreamIoAbstractWriter_H_

@class IOSClass;
@protocol ComThoughtworksXstreamIoHierarchicalStreamWriter;
@protocol ComThoughtworksXstreamIoNamingNameCoder;

#import "JreEmulation.h"
#include "com/thoughtworks/xstream/io/ExtendedHierarchicalStreamWriter.h"

@interface ComThoughtworksXstreamIoAbstractWriter : NSObject < ComThoughtworksXstreamIoExtendedHierarchicalStreamWriter > {
 @public
  id<ComThoughtworksXstreamIoNamingNameCoder> nameCoder_;
}

- (instancetype)init;

- (instancetype)initWithComThoughtworksXstreamIoNamingNameCoder:(id<ComThoughtworksXstreamIoNamingNameCoder>)nameCoder;

- (void)startNodeWithNSString:(NSString *)name
                 withIOSClass:(IOSClass *)clazz;

- (id<ComThoughtworksXstreamIoHierarchicalStreamWriter>)underlyingWriter;

- (NSString *)encodeNodeWithNSString:(NSString *)name;

- (NSString *)encodeAttributeWithNSString:(NSString *)name;

- (void)copyAllFieldsTo:(ComThoughtworksXstreamIoAbstractWriter *)other;

@end

__attribute__((always_inline)) inline void ComThoughtworksXstreamIoAbstractWriter_init() {}

J2OBJC_FIELD_SETTER(ComThoughtworksXstreamIoAbstractWriter, nameCoder_, id<ComThoughtworksXstreamIoNamingNameCoder>)

#endif // _ComThoughtworksXstreamIoAbstractWriter_H_
