//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/Zetzsche/Development/SimarisCurves/com.thoughtworks.xstream/src/com/thoughtworks/xstream/io/ExtendedHierarchicalStreamWriter.java
//

#ifndef _ComThoughtworksXstreamIoExtendedHierarchicalStreamWriter_H_
#define _ComThoughtworksXstreamIoExtendedHierarchicalStreamWriter_H_

@class IOSClass;

#import "JreEmulation.h"
#include "com/thoughtworks/xstream/io/HierarchicalStreamWriter.h"

@protocol ComThoughtworksXstreamIoExtendedHierarchicalStreamWriter < ComThoughtworksXstreamIoHierarchicalStreamWriter, NSObject, JavaObject >
- (void)startNodeWithNSString:(NSString *)name
                 withIOSClass:(IOSClass *)clazz;

@end

__attribute__((always_inline)) inline void ComThoughtworksXstreamIoExtendedHierarchicalStreamWriter_init() {}

#endif // _ComThoughtworksXstreamIoExtendedHierarchicalStreamWriter_H_
