//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/Zetzsche/Development/SimarisCurves/com.thoughtworks.xstream/bin/src/com/thoughtworks/xstream/io/xml/AbstractDocumentReader.java
//


#line 1 "/Users/Zetzsche/Development/SimarisCurves/com.thoughtworks.xstream/bin/src/com/thoughtworks/xstream/io/xml/AbstractDocumentReader.java"

#include "J2ObjC_source.h"
#include "com/thoughtworks/xstream/converters/ErrorWriter.h"
#include "com/thoughtworks/xstream/core/util/FastStack.h"
#include "com/thoughtworks/xstream/io/AttributeNameIterator.h"
#include "com/thoughtworks/xstream/io/naming/NameCoder.h"
#include "com/thoughtworks/xstream/io/xml/AbstractDocumentReader.h"
#include "com/thoughtworks/xstream/io/xml/AbstractXmlReader.h"
#include "com/thoughtworks/xstream/io/xml/XmlFriendlyNameCoder.h"
#include "com/thoughtworks/xstream/io/xml/XmlFriendlyReplacer.h"
#include "java/util/Iterator.h"

#pragma clang diagnostic ignored "-Wprotocol"

@interface ComThoughtworksXstreamIoXmlAbstractDocumentReader () {
 @public
  ComThoughtworksXstreamCoreUtilFastStack *pointers_;
  id current_;
}

@end

J2OBJC_FIELD_SETTER(ComThoughtworksXstreamIoXmlAbstractDocumentReader, pointers_, ComThoughtworksXstreamCoreUtilFastStack *)
J2OBJC_FIELD_SETTER(ComThoughtworksXstreamIoXmlAbstractDocumentReader, current_, id)

@interface ComThoughtworksXstreamIoXmlAbstractDocumentReader_Pointer : NSObject {
 @public
  jint v_;
}

- (instancetype)init;

@end

J2OBJC_EMPTY_STATIC_INIT(ComThoughtworksXstreamIoXmlAbstractDocumentReader_Pointer)

__attribute__((unused)) static void ComThoughtworksXstreamIoXmlAbstractDocumentReader_Pointer_init(ComThoughtworksXstreamIoXmlAbstractDocumentReader_Pointer *self);

__attribute__((unused)) static ComThoughtworksXstreamIoXmlAbstractDocumentReader_Pointer *new_ComThoughtworksXstreamIoXmlAbstractDocumentReader_Pointer_init() NS_RETURNS_RETAINED;

J2OBJC_TYPE_LITERAL_HEADER(ComThoughtworksXstreamIoXmlAbstractDocumentReader_Pointer)


#line 21
@implementation ComThoughtworksXstreamIoXmlAbstractDocumentReader


#line 26
- (instancetype)initWithId:(id)rootElement {
  ComThoughtworksXstreamIoXmlAbstractDocumentReader_initWithId_(self, rootElement);
  return self;
}


#line 33
- (instancetype)initWithId:(id)rootElement
withComThoughtworksXstreamIoNamingNameCoder:(id<ComThoughtworksXstreamIoNamingNameCoder>)nameCoder {
  ComThoughtworksXstreamIoXmlAbstractDocumentReader_initWithId_withComThoughtworksXstreamIoNamingNameCoder_(self, rootElement, nameCoder);
  return self;
}


#line 44
- (instancetype)initWithId:(id)rootElement
withComThoughtworksXstreamIoXmlXmlFriendlyReplacer:(ComThoughtworksXstreamIoXmlXmlFriendlyReplacer *)replacer {
  ComThoughtworksXstreamIoXmlAbstractDocumentReader_initWithId_withComThoughtworksXstreamIoXmlXmlFriendlyReplacer_(self, rootElement, replacer);
  return self;
}


#line 48
- (void)reassignCurrentElementWithId:(id)current {
  // can't call an abstract method
  [self doesNotRecognizeSelector:_cmd];
}


#line 49
- (id)getParent {
  // can't call an abstract method
  [self doesNotRecognizeSelector:_cmd];
  return 0;
}


#line 50
- (id)getChildWithInt:(jint)index {
  // can't call an abstract method
  [self doesNotRecognizeSelector:_cmd];
  return 0;
}


#line 51
- (jint)getChildCount {
  // can't call an abstract method
  [self doesNotRecognizeSelector:_cmd];
  return 0;
}

- (jboolean)hasMoreChildren {
  ComThoughtworksXstreamIoXmlAbstractDocumentReader_Pointer *pointer = (ComThoughtworksXstreamIoXmlAbstractDocumentReader_Pointer *) check_class_cast([((ComThoughtworksXstreamCoreUtilFastStack *) nil_chk(pointers_)) peek], [ComThoughtworksXstreamIoXmlAbstractDocumentReader_Pointer class]);
  
#line 60
  if (((ComThoughtworksXstreamIoXmlAbstractDocumentReader_Pointer *) nil_chk(pointer))->v_ < [self getChildCount]) {
    return YES;
  }
  else {
    
#line 63
    return NO;
  }
}


#line 67
- (void)moveUp {
  current_ = [self getParent];
  [((ComThoughtworksXstreamCoreUtilFastStack *) nil_chk(pointers_)) popSilently];
  [self reassignCurrentElementWithId:current_];
}

- (void)moveDown {
  ComThoughtworksXstreamIoXmlAbstractDocumentReader_Pointer *pointer = (ComThoughtworksXstreamIoXmlAbstractDocumentReader_Pointer *) check_class_cast([((ComThoughtworksXstreamCoreUtilFastStack *) nil_chk(pointers_)) peek], [ComThoughtworksXstreamIoXmlAbstractDocumentReader_Pointer class]);
  (void) [pointers_ pushWithId:new_ComThoughtworksXstreamIoXmlAbstractDocumentReader_Pointer_init()];
  
#line 77
  current_ = [self getChildWithInt:((ComThoughtworksXstreamIoXmlAbstractDocumentReader_Pointer *) nil_chk(pointer))->v_];
  
#line 79
  pointer->v_++;
  [self reassignCurrentElementWithId:current_];
}


#line 83
- (id<JavaUtilIterator>)getAttributeNames {
  return new_ComThoughtworksXstreamIoAttributeNameIterator_initWithComThoughtworksXstreamIoHierarchicalStreamReader_(self);
}

- (void)appendErrorsWithComThoughtworksXstreamConvertersErrorWriter:(id<ComThoughtworksXstreamConvertersErrorWriter>)errorWriter {
}

- (id)getCurrent {
  return self->current_;
}

- (void)close {
}

+ (const J2ObjcClassInfo *)__metadata {
  static const J2ObjcMethodInfo methods[] = {
    { "initWithId:", "AbstractDocumentReader", NULL, 0x4, NULL, NULL },
    { "initWithId:withComThoughtworksXstreamIoNamingNameCoder:", "AbstractDocumentReader", NULL, 0x4, NULL, NULL },
    { "initWithId:withComThoughtworksXstreamIoXmlXmlFriendlyReplacer:", "AbstractDocumentReader", NULL, 0x4, NULL, NULL },
    { "reassignCurrentElementWithId:", "reassignCurrentElement", "V", 0x404, NULL, NULL },
    { "getParent", NULL, "Ljava.lang.Object;", 0x404, NULL, NULL },
    { "getChildWithInt:", "getChild", "Ljava.lang.Object;", 0x404, NULL, NULL },
    { "getChildCount", NULL, "I", 0x404, NULL, NULL },
    { "hasMoreChildren", NULL, "Z", 0x1, NULL, NULL },
    { "moveUp", NULL, "V", 0x1, NULL, NULL },
    { "moveDown", NULL, "V", 0x1, NULL, NULL },
    { "getAttributeNames", NULL, "Ljava.util.Iterator;", 0x1, NULL, NULL },
    { "appendErrorsWithComThoughtworksXstreamConvertersErrorWriter:", "appendErrors", "V", 0x1, NULL, NULL },
    { "getCurrent", NULL, "Ljava.lang.Object;", 0x1, NULL, NULL },
    { "close", NULL, "V", 0x1, NULL, NULL },
  };
  static const J2ObjcFieldInfo fields[] = {
    { "pointers_", NULL, 0x2, "Lcom.thoughtworks.xstream.core.util.FastStack;", NULL, NULL,  },
    { "current_", NULL, 0x2, "Ljava.lang.Object;", NULL, NULL,  },
  };
  static const char *inner_classes[] = {"Lcom.thoughtworks.xstream.io.xml.AbstractDocumentReader$Pointer;"};
  static const J2ObjcClassInfo _ComThoughtworksXstreamIoXmlAbstractDocumentReader = { 2, "AbstractDocumentReader", "com.thoughtworks.xstream.io.xml", NULL, 0x401, 14, methods, 2, fields, 0, NULL, 1, inner_classes, NULL, NULL };
  return &_ComThoughtworksXstreamIoXmlAbstractDocumentReader;
}

@end


#line 26
void ComThoughtworksXstreamIoXmlAbstractDocumentReader_initWithId_(ComThoughtworksXstreamIoXmlAbstractDocumentReader *self, id rootElement) {
  (void) ComThoughtworksXstreamIoXmlAbstractDocumentReader_initWithId_withComThoughtworksXstreamIoNamingNameCoder_(self, rootElement, new_ComThoughtworksXstreamIoXmlXmlFriendlyNameCoder_init());
}


#line 33
void ComThoughtworksXstreamIoXmlAbstractDocumentReader_initWithId_withComThoughtworksXstreamIoNamingNameCoder_(ComThoughtworksXstreamIoXmlAbstractDocumentReader *self, id rootElement, id<ComThoughtworksXstreamIoNamingNameCoder> nameCoder) {
  (void) ComThoughtworksXstreamIoXmlAbstractXmlReader_initWithComThoughtworksXstreamIoNamingNameCoder_(self, nameCoder);
  self->pointers_ = new_ComThoughtworksXstreamCoreUtilFastStack_initWithInt_(
#line 23
  16);
  
#line 35
  self->current_ = rootElement;
  (void) [self->pointers_ pushWithId:new_ComThoughtworksXstreamIoXmlAbstractDocumentReader_Pointer_init()];
  [self reassignCurrentElementWithId:self->current_];
}


#line 44
void ComThoughtworksXstreamIoXmlAbstractDocumentReader_initWithId_withComThoughtworksXstreamIoXmlXmlFriendlyReplacer_(ComThoughtworksXstreamIoXmlAbstractDocumentReader *self, id rootElement, ComThoughtworksXstreamIoXmlXmlFriendlyReplacer *replacer) {
  (void) ComThoughtworksXstreamIoXmlAbstractDocumentReader_initWithId_withComThoughtworksXstreamIoNamingNameCoder_(self, rootElement, replacer);
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(ComThoughtworksXstreamIoXmlAbstractDocumentReader)


#line 53
@implementation ComThoughtworksXstreamIoXmlAbstractDocumentReader_Pointer

- (instancetype)init {
  ComThoughtworksXstreamIoXmlAbstractDocumentReader_Pointer_init(self);
  return self;
}

+ (const J2ObjcClassInfo *)__metadata {
  static const J2ObjcMethodInfo methods[] = {
    { "init", NULL, NULL, 0x2, NULL, NULL },
  };
  static const J2ObjcFieldInfo fields[] = {
    { "v_", NULL, 0x1, "I", NULL, NULL,  },
  };
  static const J2ObjcClassInfo _ComThoughtworksXstreamIoXmlAbstractDocumentReader_Pointer = { 2, "Pointer", "com.thoughtworks.xstream.io.xml", "AbstractDocumentReader", 0xa, 1, methods, 1, fields, 0, NULL, 0, NULL, NULL, NULL };
  return &_ComThoughtworksXstreamIoXmlAbstractDocumentReader_Pointer;
}

@end

void ComThoughtworksXstreamIoXmlAbstractDocumentReader_Pointer_init(ComThoughtworksXstreamIoXmlAbstractDocumentReader_Pointer *self) {
  (void) NSObject_init(self);
}

ComThoughtworksXstreamIoXmlAbstractDocumentReader_Pointer *new_ComThoughtworksXstreamIoXmlAbstractDocumentReader_Pointer_init() {
  ComThoughtworksXstreamIoXmlAbstractDocumentReader_Pointer *self = [ComThoughtworksXstreamIoXmlAbstractDocumentReader_Pointer alloc];
  ComThoughtworksXstreamIoXmlAbstractDocumentReader_Pointer_init(self);
  return self;
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(ComThoughtworksXstreamIoXmlAbstractDocumentReader_Pointer)
