//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/Zetzsche/Development/SimarisCurves/com.thoughtworks.xstream/bin/src/com/thoughtworks/xstream/io/xml/AbstractXmlDriver.java
//


#line 1 "/Users/Zetzsche/Development/SimarisCurves/com.thoughtworks.xstream/bin/src/com/thoughtworks/xstream/io/xml/AbstractXmlDriver.java"

#include "J2ObjC_source.h"
#include "com/thoughtworks/xstream/io/AbstractDriver.h"
#include "com/thoughtworks/xstream/io/naming/NameCoder.h"
#include "com/thoughtworks/xstream/io/xml/AbstractXmlDriver.h"
#include "com/thoughtworks/xstream/io/xml/XmlFriendlyNameCoder.h"
#include "com/thoughtworks/xstream/io/xml/XmlFriendlyReplacer.h"


#line 27
@implementation ComThoughtworksXstreamIoXmlAbstractXmlDriver


#line 34
- (instancetype)init {
  ComThoughtworksXstreamIoXmlAbstractXmlDriver_init(self);
  return self;
}


#line 42
- (instancetype)initWithComThoughtworksXstreamIoNamingNameCoder:(id<ComThoughtworksXstreamIoNamingNameCoder>)nameCoder {
  ComThoughtworksXstreamIoXmlAbstractXmlDriver_initWithComThoughtworksXstreamIoNamingNameCoder_(self, nameCoder);
  return self;
}


#line 52
- (instancetype)initWithComThoughtworksXstreamIoXmlXmlFriendlyReplacer:(ComThoughtworksXstreamIoXmlXmlFriendlyReplacer *)replacer {
  ComThoughtworksXstreamIoXmlAbstractXmlDriver_initWithComThoughtworksXstreamIoXmlXmlFriendlyReplacer_(self, replacer);
  return self;
}


#line 59
- (ComThoughtworksXstreamIoXmlXmlFriendlyReplacer *)xmlFriendlyReplacer {
  id<ComThoughtworksXstreamIoNamingNameCoder> nameCoder = [self getNameCoder];
  return [nameCoder isKindOfClass:[ComThoughtworksXstreamIoXmlXmlFriendlyReplacer class]] ? (ComThoughtworksXstreamIoXmlXmlFriendlyReplacer *) check_class_cast(nameCoder, [ComThoughtworksXstreamIoXmlXmlFriendlyReplacer class]) : nil;
}

+ (const J2ObjcClassInfo *)__metadata {
  static const J2ObjcMethodInfo methods[] = {
    { "init", "AbstractXmlDriver", NULL, 0x1, NULL, NULL },
    { "initWithComThoughtworksXstreamIoNamingNameCoder:", "AbstractXmlDriver", NULL, 0x1, NULL, NULL },
    { "initWithComThoughtworksXstreamIoXmlXmlFriendlyReplacer:", "AbstractXmlDriver", NULL, 0x1, NULL, NULL },
    { "xmlFriendlyReplacer", NULL, "Lcom.thoughtworks.xstream.io.xml.XmlFriendlyReplacer;", 0x4, NULL, NULL },
  };
  static const J2ObjcClassInfo _ComThoughtworksXstreamIoXmlAbstractXmlDriver = { 2, "AbstractXmlDriver", "com.thoughtworks.xstream.io.xml", NULL, 0x401, 4, methods, 0, NULL, 0, NULL, 0, NULL, NULL, NULL };
  return &_ComThoughtworksXstreamIoXmlAbstractXmlDriver;
}

@end


#line 34
void ComThoughtworksXstreamIoXmlAbstractXmlDriver_init(ComThoughtworksXstreamIoXmlAbstractXmlDriver *self) {
  (void) ComThoughtworksXstreamIoXmlAbstractXmlDriver_initWithComThoughtworksXstreamIoNamingNameCoder_(self, new_ComThoughtworksXstreamIoXmlXmlFriendlyNameCoder_init());
}


#line 42
void ComThoughtworksXstreamIoXmlAbstractXmlDriver_initWithComThoughtworksXstreamIoNamingNameCoder_(ComThoughtworksXstreamIoXmlAbstractXmlDriver *self, id<ComThoughtworksXstreamIoNamingNameCoder> nameCoder) {
  (void) ComThoughtworksXstreamIoAbstractDriver_initWithComThoughtworksXstreamIoNamingNameCoder_(self, nameCoder);
}


#line 52
void ComThoughtworksXstreamIoXmlAbstractXmlDriver_initWithComThoughtworksXstreamIoXmlXmlFriendlyReplacer_(ComThoughtworksXstreamIoXmlAbstractXmlDriver *self, ComThoughtworksXstreamIoXmlXmlFriendlyReplacer *replacer) {
  (void) ComThoughtworksXstreamIoXmlAbstractXmlDriver_initWithComThoughtworksXstreamIoNamingNameCoder_(self, replacer);
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(ComThoughtworksXstreamIoXmlAbstractXmlDriver)
