//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/Zetzsche/Development/SimarisCurves/com.thoughtworks.xstream/src/com/thoughtworks/xstream/io/xml/AbstractXmlDriver.java
//

#line 1 "/Users/Zetzsche/Development/SimarisCurves/com.thoughtworks.xstream/src/com/thoughtworks/xstream/io/xml/AbstractXmlDriver.java"

#include "com/thoughtworks/xstream/io/AbstractDriver.h"
#include "com/thoughtworks/xstream/io/naming/NameCoder.h"
#include "com/thoughtworks/xstream/io/xml/AbstractXmlDriver.h"
#include "com/thoughtworks/xstream/io/xml/XmlFriendlyNameCoder.h"
#include "com/thoughtworks/xstream/io/xml/XmlFriendlyReplacer.h"


#line 27
@implementation ComThoughtworksXstreamIoXmlAbstractXmlDriver


#line 34
- (instancetype)init {
  return
#line 35
  [self initComThoughtworksXstreamIoXmlAbstractXmlDriverWithComThoughtworksXstreamIoNamingNameCoder:[[ComThoughtworksXstreamIoXmlXmlFriendlyNameCoder alloc] init]];
}


#line 42
- (instancetype)initComThoughtworksXstreamIoXmlAbstractXmlDriverWithComThoughtworksXstreamIoNamingNameCoder:(id<ComThoughtworksXstreamIoNamingNameCoder>)nameCoder {
  return
#line 43
  [super initWithComThoughtworksXstreamIoNamingNameCoder:nameCoder];
}

- (instancetype)initWithComThoughtworksXstreamIoNamingNameCoder:(id<ComThoughtworksXstreamIoNamingNameCoder>)nameCoder {
  return [self initComThoughtworksXstreamIoXmlAbstractXmlDriverWithComThoughtworksXstreamIoNamingNameCoder:
#line 42
nameCoder];
}


#line 52
- (instancetype)initWithComThoughtworksXstreamIoXmlXmlFriendlyReplacer:(ComThoughtworksXstreamIoXmlXmlFriendlyReplacer *)replacer {
  return [self initComThoughtworksXstreamIoXmlAbstractXmlDriverWithComThoughtworksXstreamIoNamingNameCoder:(id<ComThoughtworksXstreamIoNamingNameCoder>) check_protocol_cast(replacer, @protocol(ComThoughtworksXstreamIoNamingNameCoder))];
}


#line 59
- (ComThoughtworksXstreamIoXmlXmlFriendlyReplacer *)xmlFriendlyReplacer {
  
#line 60
  id<ComThoughtworksXstreamIoNamingNameCoder> nameCoder = [self getNameCoder];
  return [(id) nameCoder isKindOfClass:[ComThoughtworksXstreamIoXmlXmlFriendlyReplacer class]] ? (ComThoughtworksXstreamIoXmlXmlFriendlyReplacer *) check_class_cast(nameCoder, [ComThoughtworksXstreamIoXmlXmlFriendlyReplacer class]) : nil;
}

+ (const J2ObjcClassInfo *)__metadata {
  static const J2ObjcMethodInfo methods[] = {
    { "init", "AbstractXmlDriver", NULL, 0x1, NULL },
    { "initWithComThoughtworksXstreamIoNamingNameCoder:", "AbstractXmlDriver", NULL, 0x1, NULL },
    { "initWithComThoughtworksXstreamIoXmlXmlFriendlyReplacer:", "AbstractXmlDriver", NULL, 0x1, NULL },
    { "xmlFriendlyReplacer", NULL, "Lcom.thoughtworks.xstream.io.xml.XmlFriendlyReplacer;", 0x4, NULL },
  };
  static const J2ObjcClassInfo _ComThoughtworksXstreamIoXmlAbstractXmlDriver = { "AbstractXmlDriver", "com.thoughtworks.xstream.io.xml", NULL, 0x401, 4, methods, 0, NULL, 0, NULL};
  return &_ComThoughtworksXstreamIoXmlAbstractXmlDriver;
}

@end
