//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/Zetzsche/Development/SimarisCurves/com.thoughtworks.xstream/src/com/thoughtworks/xstream/io/xml/DocumentWriter.java
//

#ifndef _ComThoughtworksXstreamIoXmlDocumentWriter_H_
#define _ComThoughtworksXstreamIoXmlDocumentWriter_H_

@protocol JavaUtilList;

#import "JreEmulation.h"
#include "com/thoughtworks/xstream/io/HierarchicalStreamWriter.h"

@protocol ComThoughtworksXstreamIoXmlDocumentWriter < ComThoughtworksXstreamIoHierarchicalStreamWriter, NSObject, JavaObject >
- (id<JavaUtilList>)getTopLevelNodes;

@end

__attribute__((always_inline)) inline void ComThoughtworksXstreamIoXmlDocumentWriter_init() {}

#endif // _ComThoughtworksXstreamIoXmlDocumentWriter_H_
