//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/Zetzsche/Development/SimarisCurves/com.thoughtworks.xstream/src/com/thoughtworks/xstream/io/xml/DomDriver.java
//

#ifndef _ComThoughtworksXstreamIoXmlDomDriver_H_
#define _ComThoughtworksXstreamIoXmlDomDriver_H_

@class ComThoughtworksXstreamIoXmlXmlFriendlyReplacer;
@class JavaIoFile;
@class JavaIoInputStream;
@class JavaIoOutputStream;
@class JavaIoReader;
@class JavaIoWriter;
@class JavaNetURL;
@class JavaxXmlParsersDocumentBuilderFactory;
@class OrgXmlSaxInputSource;
@protocol ComThoughtworksXstreamIoHierarchicalStreamReader;
@protocol ComThoughtworksXstreamIoHierarchicalStreamWriter;
@protocol ComThoughtworksXstreamIoNamingNameCoder;

#import "JreEmulation.h"
#include "com/thoughtworks/xstream/io/xml/AbstractXmlDriver.h"

@interface ComThoughtworksXstreamIoXmlDomDriver : ComThoughtworksXstreamIoXmlAbstractXmlDriver {
 @public
  NSString *encoding_;
  JavaxXmlParsersDocumentBuilderFactory *documentBuilderFactory_;
}

- (instancetype)init;

- (instancetype)initWithNSString:(NSString *)encoding;

- (instancetype)initWithNSString:(NSString *)encoding
withComThoughtworksXstreamIoNamingNameCoder:(id<ComThoughtworksXstreamIoNamingNameCoder>)nameCoder;

- (instancetype)initWithNSString:(NSString *)encoding
withComThoughtworksXstreamIoXmlXmlFriendlyReplacer:(ComThoughtworksXstreamIoXmlXmlFriendlyReplacer *)replacer;

- (id<ComThoughtworksXstreamIoHierarchicalStreamReader>)createReaderWithJavaIoReader:(JavaIoReader *)inArg;

- (id<ComThoughtworksXstreamIoHierarchicalStreamReader>)createReaderWithJavaIoInputStream:(JavaIoInputStream *)inArg;

- (id<ComThoughtworksXstreamIoHierarchicalStreamReader>)createReaderWithJavaNetURL:(JavaNetURL *)inArg;

- (id<ComThoughtworksXstreamIoHierarchicalStreamReader>)createReaderWithJavaIoFile:(JavaIoFile *)inArg;

- (id<ComThoughtworksXstreamIoHierarchicalStreamReader>)createReaderWithOrgXmlSaxInputSource:(OrgXmlSaxInputSource *)source;

- (id<ComThoughtworksXstreamIoHierarchicalStreamWriter>)createWriterWithJavaIoWriter:(JavaIoWriter *)outArg;

- (id<ComThoughtworksXstreamIoHierarchicalStreamWriter>)createWriterWithJavaIoOutputStream:(JavaIoOutputStream *)outArg;

- (void)copyAllFieldsTo:(ComThoughtworksXstreamIoXmlDomDriver *)other;

@end

__attribute__((always_inline)) inline void ComThoughtworksXstreamIoXmlDomDriver_init() {}

J2OBJC_FIELD_SETTER(ComThoughtworksXstreamIoXmlDomDriver, encoding_, NSString *)
J2OBJC_FIELD_SETTER(ComThoughtworksXstreamIoXmlDomDriver, documentBuilderFactory_, JavaxXmlParsersDocumentBuilderFactory *)

#endif // _ComThoughtworksXstreamIoXmlDomDriver_H_
