//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/Zetzsche/Development/SimarisCurves/com.thoughtworks.xstream/bin/src/com/thoughtworks/xstream/io/xml/DomReader.java
//

#ifndef _ComThoughtworksXstreamIoXmlDomReader_H_
#define _ComThoughtworksXstreamIoXmlDomReader_H_

#include "J2ObjC_header.h"
#include "com/thoughtworks/xstream/io/xml/AbstractDocumentReader.h"

@class ComThoughtworksXstreamIoXmlXmlFriendlyReplacer;
@protocol ComThoughtworksXstreamIoNamingNameCoder;
@protocol OrgW3cDomDocument;
@protocol OrgW3cDomElement;

@interface ComThoughtworksXstreamIoXmlDomReader : ComThoughtworksXstreamIoXmlAbstractDocumentReader

#pragma mark Public

- (instancetype)initWithOrgW3cDomDocument:(id<OrgW3cDomDocument>)document;

- (instancetype)initWithOrgW3cDomDocument:(id<OrgW3cDomDocument>)document
withComThoughtworksXstreamIoNamingNameCoder:(id<ComThoughtworksXstreamIoNamingNameCoder>)nameCoder;

- (instancetype)initWithOrgW3cDomDocument:(id<OrgW3cDomDocument>)document
withComThoughtworksXstreamIoXmlXmlFriendlyReplacer:(ComThoughtworksXstreamIoXmlXmlFriendlyReplacer *)replacer;

- (instancetype)initWithOrgW3cDomElement:(id<OrgW3cDomElement>)rootElement;

- (instancetype)initWithOrgW3cDomElement:(id<OrgW3cDomElement>)rootElement
withComThoughtworksXstreamIoNamingNameCoder:(id<ComThoughtworksXstreamIoNamingNameCoder>)nameCoder;

- (instancetype)initWithOrgW3cDomElement:(id<OrgW3cDomElement>)rootElement
withComThoughtworksXstreamIoXmlXmlFriendlyReplacer:(ComThoughtworksXstreamIoXmlXmlFriendlyReplacer *)replacer;

- (NSString *)getAttributeWithInt:(jint)index;

- (NSString *)getAttributeWithNSString:(NSString *)name;

- (jint)getAttributeCount;

- (NSString *)getAttributeNameWithInt:(jint)index;

- (NSString *)getNodeName;

- (NSString *)getValue;

- (NSString *)peekNextChild;

#pragma mark Protected

- (id)getChildWithInt:(jint)index;

- (jint)getChildCount;

- (id)getParent;

- (void)reassignCurrentElementWithId:(id)current;

@end

J2OBJC_EMPTY_STATIC_INIT(ComThoughtworksXstreamIoXmlDomReader)

FOUNDATION_EXPORT void ComThoughtworksXstreamIoXmlDomReader_initWithOrgW3cDomElement_(ComThoughtworksXstreamIoXmlDomReader *self, id<OrgW3cDomElement> rootElement);

FOUNDATION_EXPORT ComThoughtworksXstreamIoXmlDomReader *new_ComThoughtworksXstreamIoXmlDomReader_initWithOrgW3cDomElement_(id<OrgW3cDomElement> rootElement) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT void ComThoughtworksXstreamIoXmlDomReader_initWithOrgW3cDomDocument_(ComThoughtworksXstreamIoXmlDomReader *self, id<OrgW3cDomDocument> document);

FOUNDATION_EXPORT ComThoughtworksXstreamIoXmlDomReader *new_ComThoughtworksXstreamIoXmlDomReader_initWithOrgW3cDomDocument_(id<OrgW3cDomDocument> document) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT void ComThoughtworksXstreamIoXmlDomReader_initWithOrgW3cDomElement_withComThoughtworksXstreamIoNamingNameCoder_(ComThoughtworksXstreamIoXmlDomReader *self, id<OrgW3cDomElement> rootElement, id<ComThoughtworksXstreamIoNamingNameCoder> nameCoder);

FOUNDATION_EXPORT ComThoughtworksXstreamIoXmlDomReader *new_ComThoughtworksXstreamIoXmlDomReader_initWithOrgW3cDomElement_withComThoughtworksXstreamIoNamingNameCoder_(id<OrgW3cDomElement> rootElement, id<ComThoughtworksXstreamIoNamingNameCoder> nameCoder) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT void ComThoughtworksXstreamIoXmlDomReader_initWithOrgW3cDomDocument_withComThoughtworksXstreamIoNamingNameCoder_(ComThoughtworksXstreamIoXmlDomReader *self, id<OrgW3cDomDocument> document, id<ComThoughtworksXstreamIoNamingNameCoder> nameCoder);

FOUNDATION_EXPORT ComThoughtworksXstreamIoXmlDomReader *new_ComThoughtworksXstreamIoXmlDomReader_initWithOrgW3cDomDocument_withComThoughtworksXstreamIoNamingNameCoder_(id<OrgW3cDomDocument> document, id<ComThoughtworksXstreamIoNamingNameCoder> nameCoder) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT void ComThoughtworksXstreamIoXmlDomReader_initWithOrgW3cDomElement_withComThoughtworksXstreamIoXmlXmlFriendlyReplacer_(ComThoughtworksXstreamIoXmlDomReader *self, id<OrgW3cDomElement> rootElement, ComThoughtworksXstreamIoXmlXmlFriendlyReplacer *replacer);

FOUNDATION_EXPORT ComThoughtworksXstreamIoXmlDomReader *new_ComThoughtworksXstreamIoXmlDomReader_initWithOrgW3cDomElement_withComThoughtworksXstreamIoXmlXmlFriendlyReplacer_(id<OrgW3cDomElement> rootElement, ComThoughtworksXstreamIoXmlXmlFriendlyReplacer *replacer) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT void ComThoughtworksXstreamIoXmlDomReader_initWithOrgW3cDomDocument_withComThoughtworksXstreamIoXmlXmlFriendlyReplacer_(ComThoughtworksXstreamIoXmlDomReader *self, id<OrgW3cDomDocument> document, ComThoughtworksXstreamIoXmlXmlFriendlyReplacer *replacer);

FOUNDATION_EXPORT ComThoughtworksXstreamIoXmlDomReader *new_ComThoughtworksXstreamIoXmlDomReader_initWithOrgW3cDomDocument_withComThoughtworksXstreamIoXmlXmlFriendlyReplacer_(id<OrgW3cDomDocument> document, ComThoughtworksXstreamIoXmlXmlFriendlyReplacer *replacer) NS_RETURNS_RETAINED;

J2OBJC_TYPE_LITERAL_HEADER(ComThoughtworksXstreamIoXmlDomReader)

#endif // _ComThoughtworksXstreamIoXmlDomReader_H_
