//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/Zetzsche/Development/SimarisCurves/com.thoughtworks.xstream/src/com/thoughtworks/xstream/io/xml/KXml2DomDriver.java
//

#ifndef _ComThoughtworksXstreamIoXmlKXml2DomDriver_H_
#define _ComThoughtworksXstreamIoXmlKXml2DomDriver_H_

@protocol ComThoughtworksXstreamIoNamingNameCoder;
@protocol OrgXmlpullV1XmlPullParser;

#import "JreEmulation.h"
#include "com/thoughtworks/xstream/io/xml/AbstractXppDomDriver.h"

@interface ComThoughtworksXstreamIoXmlKXml2DomDriver : ComThoughtworksXstreamIoXmlAbstractXppDomDriver {
}

- (instancetype)init;

- (instancetype)initWithComThoughtworksXstreamIoNamingNameCoder:(id<ComThoughtworksXstreamIoNamingNameCoder>)nameCoder;

- (id<OrgXmlpullV1XmlPullParser>)createParser;

@end

__attribute__((always_inline)) inline void ComThoughtworksXstreamIoXmlKXml2DomDriver_init() {}

#endif // _ComThoughtworksXstreamIoXmlKXml2DomDriver_H_
