//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/Zetzsche/Development/SimarisCurves/com.thoughtworks.xstream/bin/src/com/thoughtworks/xstream/annotations/AnnotationProvider.java
//

#ifndef _ComThoughtworksXstreamAnnotationsAnnotationProvider_H_
#define _ComThoughtworksXstreamAnnotationsAnnotationProvider_H_

#include "J2ObjC_header.h"

@class IOSClass;
@class JavaLangReflectField;
@protocol JavaLangAnnotationAnnotation;

@interface ComThoughtworksXstreamAnnotationsAnnotationProvider : NSObject

#pragma mark Public

- (instancetype)init;

- (id)getAnnotationWithJavaLangReflectField:(JavaLangReflectField *)field
                               withIOSClass:(IOSClass *)annotationClass;

@end

J2OBJC_EMPTY_STATIC_INIT(ComThoughtworksXstreamAnnotationsAnnotationProvider)

FOUNDATION_EXPORT void ComThoughtworksXstreamAnnotationsAnnotationProvider_init(ComThoughtworksXstreamAnnotationsAnnotationProvider *self);

FOUNDATION_EXPORT ComThoughtworksXstreamAnnotationsAnnotationProvider *new_ComThoughtworksXstreamAnnotationsAnnotationProvider_init() NS_RETURNS_RETAINED;

J2OBJC_TYPE_LITERAL_HEADER(ComThoughtworksXstreamAnnotationsAnnotationProvider)

#endif // _ComThoughtworksXstreamAnnotationsAnnotationProvider_H_
