//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/Zetzsche/Development/SimarisCurves/com.thoughtworks.xstream/src/com/thoughtworks/xstream/annotations/XStreamImplicitCollection.java
//

#ifndef _ComThoughtworksXstreamAnnotationsXStreamImplicitCollection_H_
#define _ComThoughtworksXstreamAnnotationsXStreamImplicitCollection_H_

#import "JreEmulation.h"
#include "java/lang/annotation/Annotation.h"

@protocol ComThoughtworksXstreamAnnotationsXStreamImplicitCollection < JavaLangAnnotationAnnotation >

@property (readonly) NSString *value;
@property (readonly) NSString *item;


@end

@interface ComThoughtworksXstreamAnnotationsXStreamImplicitCollection : NSObject < ComThoughtworksXstreamAnnotationsXStreamImplicitCollection > {
 @private
  NSString *value;
  NSString *item;
}

- (instancetype)initWithItem:(NSString *)item_ withValue:(NSString *)value_;

+ (NSString *)itemDefault;

@end

__attribute__((always_inline)) inline void ComThoughtworksXstreamAnnotationsXStreamImplicitCollection_init() {}

#endif // _ComThoughtworksXstreamAnnotationsXStreamImplicitCollection_H_
