//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/Zetzsche/Development/SimarisCurves/com.thoughtworks.xstream/bin/src/com/thoughtworks/xstream/annotations/XStreamConverters.java
//

#ifndef _ComThoughtworksXstreamAnnotationsXStreamConverters_H_
#define _ComThoughtworksXstreamAnnotationsXStreamConverters_H_

#include "J2ObjC_header.h"
#include "java/lang/annotation/Annotation.h"

@class IOSObjectArray;

@protocol ComThoughtworksXstreamAnnotationsXStreamConverters < JavaLangAnnotationAnnotation >

@property (readonly) IOSObjectArray *value;

@end

@interface ComThoughtworksXstreamAnnotationsXStreamConverters : NSObject < ComThoughtworksXstreamAnnotationsXStreamConverters > {
 @private
  IOSObjectArray *value_;
}

- (instancetype)initWithValue:(IOSObjectArray *)value__;

@end

J2OBJC_EMPTY_STATIC_INIT(ComThoughtworksXstreamAnnotationsXStreamConverters)

J2OBJC_TYPE_LITERAL_HEADER(ComThoughtworksXstreamAnnotationsXStreamConverters)

#endif // _ComThoughtworksXstreamAnnotationsXStreamConverters_H_
