//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/Zetzsche/Development/SimarisCurves/com.thoughtworks.xstream/src/com/thoughtworks/xstream/core/util/ArrayIterator.java
//

#line 1 "/Users/Zetzsche/Development/SimarisCurves/com.thoughtworks.xstream/src/com/thoughtworks/xstream/core/util/ArrayIterator.java"

#include "com/thoughtworks/xstream/core/util/ArrayIterator.h"
#include "java/lang/UnsupportedOperationException.h"
#include "java/lang/reflect/Array.h"


#line 21
@implementation ComThoughtworksXstreamCoreUtilArrayIterator


#line 25
- (instancetype)initWithId:(id)array {
  if (self = [super init]) {
    
#line 26
    self->array_ = array;
    
#line 27
    length_ = [JavaLangReflectArray getLengthWithId:array];
  }
  return self;
}


#line 30
- (jboolean)hasNext {
  
#line 31
  return idx_ < length_;
}


#line 34
- (id)next {
  
#line 35
  return [JavaLangReflectArray getWithId:array_ withInt:idx_++];
}


#line 38
- (void)remove {
  
#line 39
  @throw [[JavaLangUnsupportedOperationException alloc] initWithNSString:@"Remove from array"];
}

- (void)copyAllFieldsTo:(ComThoughtworksXstreamCoreUtilArrayIterator *)other {
  [super copyAllFieldsTo:other];
  other->array_ = array_;
  other->idx_ = idx_;
  other->length_ = length_;
}

+ (const J2ObjcClassInfo *)__metadata {
  static const J2ObjcMethodInfo methods[] = {
    { "initWithId:", "ArrayIterator", NULL, 0x1, NULL },
    { "hasNext", NULL, "Z", 0x1, NULL },
    { "next", NULL, "Ljava.lang.Object;", 0x1, NULL },
    { "remove", NULL, "V", 0x1, NULL },
  };
  static const J2ObjcFieldInfo fields[] = {
    { "array_", NULL, 0x12, "Ljava.lang.Object;", NULL,  },
    { "idx_", NULL, 0x2, "I", NULL,  },
    { "length_", NULL, 0x2, "I", NULL,  },
  };
  static const J2ObjcClassInfo _ComThoughtworksXstreamCoreUtilArrayIterator = { "ArrayIterator", "com.thoughtworks.xstream.core.util", NULL, 0x1, 4, methods, 3, fields, 0, NULL};
  return &_ComThoughtworksXstreamCoreUtilArrayIterator;
}

@end
