//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/Zetzsche/Development/SimarisCurves/com.thoughtworks.xstream/bin/src/com/thoughtworks/xstream/core/util/PresortedMap.java
//

#ifndef _ComThoughtworksXstreamCoreUtilPresortedMap_H_
#define _ComThoughtworksXstreamCoreUtilPresortedMap_H_

#include "J2ObjC_header.h"
#include "java/util/SortedMap.h"

@protocol JavaUtilCollection;
@protocol JavaUtilComparator;
@protocol JavaUtilMap;
@protocol JavaUtilSet;

@interface ComThoughtworksXstreamCoreUtilPresortedMap : NSObject < JavaUtilSortedMap >

#pragma mark Public

- (instancetype)init;

- (instancetype)initWithJavaUtilComparator:(id<JavaUtilComparator>)comparator;

- (void)clear;

- (id<JavaUtilComparator>)comparator;

- (jboolean)containsKeyWithId:(id)key;

- (jboolean)containsValueWithId:(id)value;

- (id<JavaUtilSet>)entrySet;

- (id)firstKey;

- (id)getWithId:(id)key;

- (id<JavaUtilSortedMap>)headMapWithId:(id)toKey;

- (jboolean)isEmpty;

- (id<JavaUtilSet>)keySet;

- (id)lastKey;

- (id)putWithId:(id)key
         withId:(id)value;

- (void)putAllWithJavaUtilMap:(id<JavaUtilMap>)m;

- (id)removeWithId:(id)key;

- (jint)size;

- (id<JavaUtilSortedMap>)subMapWithId:(id)fromKey
                               withId:(id)toKey;

- (id<JavaUtilSortedMap>)tailMapWithId:(id)fromKey;

- (id<JavaUtilCollection>)values;

@end

J2OBJC_EMPTY_STATIC_INIT(ComThoughtworksXstreamCoreUtilPresortedMap)

FOUNDATION_EXPORT void ComThoughtworksXstreamCoreUtilPresortedMap_init(ComThoughtworksXstreamCoreUtilPresortedMap *self);

FOUNDATION_EXPORT ComThoughtworksXstreamCoreUtilPresortedMap *new_ComThoughtworksXstreamCoreUtilPresortedMap_init() NS_RETURNS_RETAINED;

FOUNDATION_EXPORT void ComThoughtworksXstreamCoreUtilPresortedMap_initWithJavaUtilComparator_(ComThoughtworksXstreamCoreUtilPresortedMap *self, id<JavaUtilComparator> comparator);

FOUNDATION_EXPORT ComThoughtworksXstreamCoreUtilPresortedMap *new_ComThoughtworksXstreamCoreUtilPresortedMap_initWithJavaUtilComparator_(id<JavaUtilComparator> comparator) NS_RETURNS_RETAINED;

J2OBJC_TYPE_LITERAL_HEADER(ComThoughtworksXstreamCoreUtilPresortedMap)

#endif // _ComThoughtworksXstreamCoreUtilPresortedMap_H_
