//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/Zetzsche/Development/SimarisCurves/com.thoughtworks.xstream/src/com/thoughtworks/xstream/core/util/TypedNull.java
//

#ifndef _ComThoughtworksXstreamCoreUtilTypedNull_H_
#define _ComThoughtworksXstreamCoreUtilTypedNull_H_

@class IOSClass;

#import "JreEmulation.h"

@interface ComThoughtworksXstreamCoreUtilTypedNull : NSObject {
 @public
  IOSClass *type_;
}

- (instancetype)initWithIOSClass:(IOSClass *)type;

- (IOSClass *)getType;

- (void)copyAllFieldsTo:(ComThoughtworksXstreamCoreUtilTypedNull *)other;

@end

__attribute__((always_inline)) inline void ComThoughtworksXstreamCoreUtilTypedNull_init() {}

J2OBJC_FIELD_SETTER(ComThoughtworksXstreamCoreUtilTypedNull, type_, IOSClass *)

#endif // _ComThoughtworksXstreamCoreUtilTypedNull_H_
