//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/Zetzsche/Development/SimarisCurves/com.thoughtworks.xstream/gen/com/example/com/thoughtworks/xstream/R.java
//

#line 1 "/Users/Zetzsche/Development/SimarisCurves/com.thoughtworks.xstream/gen/com/example/com/thoughtworks/xstream/R.java"

#include "com/example/com/thoughtworks/xstream/R.h"


#line 10
@implementation ComExampleComThoughtworksXstreamR

- (instancetype)init {
  return [super init];
}

+ (const J2ObjcClassInfo *)__metadata {
  static const J2ObjcMethodInfo methods[] = {
    { "init", NULL, NULL, 0x1, NULL },
  };
  static const J2ObjcClassInfo _ComExampleComThoughtworksXstreamR = { "R", "com.example.com.thoughtworks.xstream", NULL, 0x11, 1, methods, 0, NULL, 0, NULL};
  return &_ComExampleComThoughtworksXstreamR;
}

@end


#line 11
@implementation ComExampleComThoughtworksXstreamR_attr

- (instancetype)init {
  return [super init];
}

+ (const J2ObjcClassInfo *)__metadata {
  static const J2ObjcMethodInfo methods[] = {
    { "init", NULL, NULL, 0x1, NULL },
  };
  static const J2ObjcClassInfo _ComExampleComThoughtworksXstreamR_attr = { "attr", "com.example.com.thoughtworks.xstream", "R", 0x19, 1, methods, 0, NULL, 0, NULL};
  return &_ComExampleComThoughtworksXstreamR_attr;
}

@end


#line 13
@implementation ComExampleComThoughtworksXstreamR_drawable

jint ComExampleComThoughtworksXstreamR_drawable_ic_launcher_ = 
#line 14
(jint) 0x7f020000;

- (instancetype)init {
  return [super init];
}

+ (const J2ObjcClassInfo *)__metadata {
  static const J2ObjcMethodInfo methods[] = {
    { "init", NULL, NULL, 0x1, NULL },
  };
  static const J2ObjcFieldInfo fields[] = {
    { "ic_launcher_", NULL, 0x9, "I", &ComExampleComThoughtworksXstreamR_drawable_ic_launcher_,  },
  };
  static const J2ObjcClassInfo _ComExampleComThoughtworksXstreamR_drawable = { "drawable", "com.example.com.thoughtworks.xstream", "R", 0x19, 1, methods, 1, fields, 0, NULL};
  return &_ComExampleComThoughtworksXstreamR_drawable;
}

@end


#line 16
@implementation ComExampleComThoughtworksXstreamR_string

jint ComExampleComThoughtworksXstreamR_string_app_name_ = 
#line 17
(jint) 0x7f030000;

- (instancetype)init {
  return [super init];
}

+ (const J2ObjcClassInfo *)__metadata {
  static const J2ObjcMethodInfo methods[] = {
    { "init", NULL, NULL, 0x1, NULL },
  };
  static const J2ObjcFieldInfo fields[] = {
    { "app_name_", NULL, 0x9, "I", &ComExampleComThoughtworksXstreamR_string_app_name_,  },
  };
  static const J2ObjcClassInfo _ComExampleComThoughtworksXstreamR_string = { "string", "com.example.com.thoughtworks.xstream", "R", 0x19, 1, methods, 1, fields, 0, NULL};
  return &_ComExampleComThoughtworksXstreamR_string;
}

@end


#line 19
@implementation ComExampleComThoughtworksXstreamR_style

jint ComExampleComThoughtworksXstreamR_style_AppBaseTheme_ = 
#line 41
(jint) 0x7f040000;
jint ComExampleComThoughtworksXstreamR_style_AppTheme_ = 
#line 45
(jint) 0x7f040001;

- (instancetype)init {
  return [super init];
}

+ (const J2ObjcClassInfo *)__metadata {
  static const J2ObjcMethodInfo methods[] = {
    { "init", NULL, NULL, 0x1, NULL },
  };
  static const J2ObjcFieldInfo fields[] = {
    { "AppBaseTheme_", NULL, 0x9, "I", &ComExampleComThoughtworksXstreamR_style_AppBaseTheme_,  },
    { "AppTheme_", NULL, 0x9, "I", &ComExampleComThoughtworksXstreamR_style_AppTheme_,  },
  };
  static const J2ObjcClassInfo _ComExampleComThoughtworksXstreamR_style = { "style", "com.example.com.thoughtworks.xstream", "R", 0x19, 1, methods, 2, fields, 0, NULL};
  return &_ComExampleComThoughtworksXstreamR_style;
}

@end
