//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/Zetzsche/Development/SimarisCurves/com.thoughtworks.xstream/src/com/thoughtworks/xstream/mapper/AttributeAliasingMapper.java
//

#line 1 "/Users/Zetzsche/Development/SimarisCurves/com.thoughtworks.xstream/src/com/thoughtworks/xstream/mapper/AttributeAliasingMapper.java"

#include "com/thoughtworks/xstream/mapper/AttributeAliasingMapper.h"
#include "com/thoughtworks/xstream/mapper/Mapper.h"
#include "java/util/Map.h"


#line 23
@implementation ComThoughtworksXstreamMapperAttributeAliasingMapper

- (instancetype)initWithComThoughtworksXstreamMapperMapper:(id<ComThoughtworksXstreamMapperMapper>)wrapped {
  return
#line 26
  [super initWithComThoughtworksXstreamMapperMapper:wrapped];
}


#line 29
- (NSString *)aliasForAttributeWithNSString:(NSString *)attribute {
  
#line 30
  NSString *alias = (NSString *) check_class_cast([((id<JavaUtilMap>) nil_chk(nameToAlias_)) getWithId:attribute], [NSString class]);
  return alias == nil ? [super aliasForAttributeWithNSString:attribute] : alias;
}


#line 34
- (NSString *)attributeForAliasWithNSString:(NSString *)alias {
  
#line 35
  NSString *name = (NSString *) check_class_cast([((id<JavaUtilMap>) nil_chk(aliasToName_)) getWithId:alias], [NSString class]);
  return name == nil ? [super attributeForAliasWithNSString:alias] : name;
}

+ (const J2ObjcClassInfo *)__metadata {
  static const J2ObjcMethodInfo methods[] = {
    { "initWithComThoughtworksXstreamMapperMapper:", "AttributeAliasingMapper", NULL, 0x1, NULL },
    { "aliasForAttributeWithNSString:", "aliasForAttribute", "Ljava.lang.String;", 0x1, NULL },
    { "attributeForAliasWithNSString:", "attributeForAlias", "Ljava.lang.String;", 0x1, NULL },
  };
  static const J2ObjcClassInfo _ComThoughtworksXstreamMapperAttributeAliasingMapper = { "AttributeAliasingMapper", "com.thoughtworks.xstream.mapper", NULL, 0x1, 3, methods, 0, NULL, 0, NULL};
  return &_ComThoughtworksXstreamMapperAttributeAliasingMapper;
}

@end
