//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/Zetzsche/Development/SimarisCurves/com.thoughtworks.xstream/src/com/thoughtworks/xstream/mapper/AttributeMapper.java
//

#ifndef _ComThoughtworksXstreamMapperAttributeMapper_H_
#define _ComThoughtworksXstreamMapperAttributeMapper_H_

@class IOSClass;
@class JavaLangReflectField;
@protocol ComThoughtworksXstreamConvertersConverterLookup;
@protocol ComThoughtworksXstreamConvertersReflectionReflectionProvider;
@protocol ComThoughtworksXstreamConvertersSingleValueConverter;
@protocol ComThoughtworksXstreamMapperMapper;
@protocol JavaUtilMap;
@protocol JavaUtilSet;

#import "JreEmulation.h"
#include "com/thoughtworks/xstream/mapper/MapperWrapper.h"

@interface ComThoughtworksXstreamMapperAttributeMapper : ComThoughtworksXstreamMapperMapperWrapper {
 @public
  id<JavaUtilMap> fieldNameToTypeMap_;
  id<JavaUtilSet> typeSet_;
  id<ComThoughtworksXstreamConvertersConverterLookup> converterLookup_;
  id<ComThoughtworksXstreamConvertersReflectionReflectionProvider> reflectionProvider_;
  id<JavaUtilSet> fieldToUseAsAttribute_;
}

- (instancetype)initWithComThoughtworksXstreamMapperMapper:(id<ComThoughtworksXstreamMapperMapper>)wrapped;

- (instancetype)initWithComThoughtworksXstreamMapperMapper:(id<ComThoughtworksXstreamMapperMapper>)wrapped
       withComThoughtworksXstreamConvertersConverterLookup:(id<ComThoughtworksXstreamConvertersConverterLookup>)converterLookup
withComThoughtworksXstreamConvertersReflectionReflectionProvider:(id<ComThoughtworksXstreamConvertersReflectionReflectionProvider>)refProvider;

- (void)setConverterLookupWithComThoughtworksXstreamConvertersConverterLookup:(id<ComThoughtworksXstreamConvertersConverterLookup>)converterLookup;

- (void)addAttributeForWithNSString:(NSString *)fieldName
                       withIOSClass:(IOSClass *)type;

- (void)addAttributeForWithIOSClass:(IOSClass *)type;

- (id<ComThoughtworksXstreamConvertersSingleValueConverter>)getLocalConverterFromItemTypeWithIOSClass:(IOSClass *)type;

- (id<ComThoughtworksXstreamConvertersSingleValueConverter>)getConverterFromItemTypeWithNSString:(NSString *)fieldName
                                                                                    withIOSClass:(IOSClass *)type;

- (id<ComThoughtworksXstreamConvertersSingleValueConverter>)getConverterFromItemTypeWithNSString:(NSString *)fieldName
                                                                                    withIOSClass:(IOSClass *)type
                                                                                    withIOSClass:(IOSClass *)definedIn;

- (jboolean)shouldLookForSingleValueConverterWithNSString:(NSString *)fieldName
                                             withIOSClass:(IOSClass *)type
                                             withIOSClass:(IOSClass *)definedIn;

- (id<ComThoughtworksXstreamConvertersSingleValueConverter>)getConverterFromItemTypeWithIOSClass:(IOSClass *)type;

- (id<ComThoughtworksXstreamConvertersSingleValueConverter>)getConverterFromAttributeWithNSString:(NSString *)attributeName;

- (id<ComThoughtworksXstreamConvertersSingleValueConverter>)getConverterFromAttributeWithIOSClass:(IOSClass *)definedIn
                                                                                     withNSString:(NSString *)attribute;

- (id<ComThoughtworksXstreamConvertersSingleValueConverter>)getConverterFromAttributeWithIOSClass:(IOSClass *)definedIn
                                                                                     withNSString:(NSString *)attribute
                                                                                     withIOSClass:(IOSClass *)type;

- (void)addAttributeForWithJavaLangReflectField:(JavaLangReflectField *)field;

- (void)addAttributeForWithIOSClass:(IOSClass *)definedIn
                       withNSString:(NSString *)fieldName;

- (void)copyAllFieldsTo:(ComThoughtworksXstreamMapperAttributeMapper *)other;

@end

__attribute__((always_inline)) inline void ComThoughtworksXstreamMapperAttributeMapper_init() {}

J2OBJC_FIELD_SETTER(ComThoughtworksXstreamMapperAttributeMapper, fieldNameToTypeMap_, id<JavaUtilMap>)
J2OBJC_FIELD_SETTER(ComThoughtworksXstreamMapperAttributeMapper, typeSet_, id<JavaUtilSet>)
J2OBJC_FIELD_SETTER(ComThoughtworksXstreamMapperAttributeMapper, converterLookup_, id<ComThoughtworksXstreamConvertersConverterLookup>)
J2OBJC_FIELD_SETTER(ComThoughtworksXstreamMapperAttributeMapper, reflectionProvider_, id<ComThoughtworksXstreamConvertersReflectionReflectionProvider>)
J2OBJC_FIELD_SETTER(ComThoughtworksXstreamMapperAttributeMapper, fieldToUseAsAttribute_, id<JavaUtilSet>)

#endif // _ComThoughtworksXstreamMapperAttributeMapper_H_
