//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/Zetzsche/Development/SimarisCurves/com.thoughtworks.xstream/bin/src/com/thoughtworks/xstream/mapper/CachingMapper.java
//

#ifndef _ComThoughtworksXstreamMapperCachingMapper_H_
#define _ComThoughtworksXstreamMapperCachingMapper_H_

#include "J2ObjC_header.h"
#include "com/thoughtworks/xstream/core/Caching.h"
#include "com/thoughtworks/xstream/mapper/MapperWrapper.h"

@class IOSClass;
@protocol ComThoughtworksXstreamMapperMapper;

@interface ComThoughtworksXstreamMapperCachingMapper : ComThoughtworksXstreamMapperMapperWrapper < ComThoughtworksXstreamCoreCaching >

#pragma mark Public

- (instancetype)initWithComThoughtworksXstreamMapperMapper:(id<ComThoughtworksXstreamMapperMapper>)wrapped;

- (void)flushCache;

- (IOSClass *)realClassWithNSString:(NSString *)elementName;

@end

J2OBJC_EMPTY_STATIC_INIT(ComThoughtworksXstreamMapperCachingMapper)

FOUNDATION_EXPORT void ComThoughtworksXstreamMapperCachingMapper_initWithComThoughtworksXstreamMapperMapper_(ComThoughtworksXstreamMapperCachingMapper *self, id<ComThoughtworksXstreamMapperMapper> wrapped);

FOUNDATION_EXPORT ComThoughtworksXstreamMapperCachingMapper *new_ComThoughtworksXstreamMapperCachingMapper_initWithComThoughtworksXstreamMapperMapper_(id<ComThoughtworksXstreamMapperMapper> wrapped) NS_RETURNS_RETAINED;

J2OBJC_TYPE_LITERAL_HEADER(ComThoughtworksXstreamMapperCachingMapper)

#endif // _ComThoughtworksXstreamMapperCachingMapper_H_
