//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/Zetzsche/Development/SimarisCurves/com.thoughtworks.xstream/bin/src/com/thoughtworks/xstream/mapper/CannotResolveClassException.java
//

#ifndef _ComThoughtworksXstreamMapperCannotResolveClassException_H_
#define _ComThoughtworksXstreamMapperCannotResolveClassException_H_

#include "J2ObjC_header.h"
#include "com/thoughtworks/xstream/XStreamException.h"

@class JavaLangThrowable;

@interface ComThoughtworksXstreamMapperCannotResolveClassException : ComThoughtworksXstreamXStreamException

#pragma mark Public

- (instancetype)initWithNSString:(NSString *)className_;

- (instancetype)initWithNSString:(NSString *)className_
           withJavaLangThrowable:(JavaLangThrowable *)cause;

@end

J2OBJC_EMPTY_STATIC_INIT(ComThoughtworksXstreamMapperCannotResolveClassException)

FOUNDATION_EXPORT void ComThoughtworksXstreamMapperCannotResolveClassException_initWithNSString_(ComThoughtworksXstreamMapperCannotResolveClassException *self, NSString *className_);

FOUNDATION_EXPORT ComThoughtworksXstreamMapperCannotResolveClassException *new_ComThoughtworksXstreamMapperCannotResolveClassException_initWithNSString_(NSString *className_) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT void ComThoughtworksXstreamMapperCannotResolveClassException_initWithNSString_withJavaLangThrowable_(ComThoughtworksXstreamMapperCannotResolveClassException *self, NSString *className_, JavaLangThrowable *cause);

FOUNDATION_EXPORT ComThoughtworksXstreamMapperCannotResolveClassException *new_ComThoughtworksXstreamMapperCannotResolveClassException_initWithNSString_withJavaLangThrowable_(NSString *className_, JavaLangThrowable *cause) NS_RETURNS_RETAINED;

J2OBJC_TYPE_LITERAL_HEADER(ComThoughtworksXstreamMapperCannotResolveClassException)

#endif // _ComThoughtworksXstreamMapperCannotResolveClassException_H_
