//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/Zetzsche/Development/SimarisCurves/com.thoughtworks.xstream/src/com/thoughtworks/xstream/mapper/DynamicProxyMapper.java
//

#line 1 "/Users/Zetzsche/Development/SimarisCurves/com.thoughtworks.xstream/src/com/thoughtworks/xstream/mapper/DynamicProxyMapper.java"

#include "IOSClass.h"
#include "com/thoughtworks/xstream/mapper/DynamicProxyMapper.h"
#include "com/thoughtworks/xstream/mapper/Mapper.h"
#include "java/lang/reflect/Proxy.h"


#line 22
@implementation ComThoughtworksXstreamMapperDynamicProxyMapper


#line 26
- (instancetype)initWithComThoughtworksXstreamMapperMapper:(id<ComThoughtworksXstreamMapperMapper>)wrapped {
  return
#line 27
  [self initComThoughtworksXstreamMapperDynamicProxyMapperWithComThoughtworksXstreamMapperMapper:wrapped withNSString:@"dynamic-proxy"];
}


#line 30
- (instancetype)initComThoughtworksXstreamMapperDynamicProxyMapperWithComThoughtworksXstreamMapperMapper:(id<ComThoughtworksXstreamMapperMapper>)wrapped
                                                                                            withNSString:(NSString *)alias {
  if (self = [super initWithComThoughtworksXstreamMapperMapper:wrapped]) {
    
#line 32
    self->alias_ = alias;
  }
  return self;
}

- (instancetype)initWithComThoughtworksXstreamMapperMapper:(id<ComThoughtworksXstreamMapperMapper>)wrapped
                                              withNSString:(NSString *)alias {
  return [self initComThoughtworksXstreamMapperDynamicProxyMapperWithComThoughtworksXstreamMapperMapper:
#line 30
wrapped withNSString:alias];
}


#line 35
- (NSString *)getAlias {
  
#line 36
  return alias_;
}


#line 39
- (void)setAliasWithNSString:(NSString *)alias {
  
#line 40
  self->alias_ = alias;
}


#line 43
- (NSString *)serializedClassWithIOSClass:(IOSClass *)type {
  
#line 44
  if ([JavaLangReflectProxy isProxyClassWithIOSClass:type]) {
    return alias_;
  }
  else {
    
#line 47
    return [super serializedClassWithIOSClass:type];
  }
}


#line 51
- (IOSClass *)realClassWithNSString:(NSString *)elementName {
  
#line 52
  if ([((NSString *) nil_chk(elementName)) isEqual:alias_]) {
    return [IOSClass classWithClass:[ComThoughtworksXstreamMapperDynamicProxyMapper_DynamicProxy class]];
  }
  else {
    
#line 55
    return [super realClassWithNSString:elementName];
  }
}

- (void)copyAllFieldsTo:(ComThoughtworksXstreamMapperDynamicProxyMapper *)other {
  [super copyAllFieldsTo:other];
  other->alias_ = alias_;
}

+ (const J2ObjcClassInfo *)__metadata {
  static const J2ObjcMethodInfo methods[] = {
    { "initWithComThoughtworksXstreamMapperMapper:", "DynamicProxyMapper", NULL, 0x1, NULL },
    { "initWithComThoughtworksXstreamMapperMapper:withNSString:", "DynamicProxyMapper", NULL, 0x1, NULL },
    { "getAlias", NULL, "Ljava.lang.String;", 0x1, NULL },
    { "setAliasWithNSString:", "setAlias", "V", 0x1, NULL },
    { "serializedClassWithIOSClass:", "serializedClass", "Ljava.lang.String;", 0x1, NULL },
    { "realClassWithNSString:", "realClass", "Ljava.lang.Class;", 0x1, NULL },
  };
  static const J2ObjcFieldInfo fields[] = {
    { "alias_", NULL, 0x2, "Ljava.lang.String;", NULL,  },
  };
  static const J2ObjcClassInfo _ComThoughtworksXstreamMapperDynamicProxyMapper = { "DynamicProxyMapper", "com.thoughtworks.xstream.mapper", NULL, 0x1, 6, methods, 1, fields, 0, NULL};
  return &_ComThoughtworksXstreamMapperDynamicProxyMapper;
}

@end


#line 62
@implementation ComThoughtworksXstreamMapperDynamicProxyMapper_DynamicProxy

- (instancetype)init {
  return [super init];
}

+ (const J2ObjcClassInfo *)__metadata {
  static const J2ObjcMethodInfo methods[] = {
    { "init", NULL, NULL, 0x1, NULL },
  };
  static const J2ObjcClassInfo _ComThoughtworksXstreamMapperDynamicProxyMapper_DynamicProxy = { "DynamicProxy", "com.thoughtworks.xstream.mapper", "DynamicProxyMapper", 0x9, 1, methods, 0, NULL, 0, NULL};
  return &_ComThoughtworksXstreamMapperDynamicProxyMapper_DynamicProxy;
}

@end
