//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/Zetzsche/Development/SimarisCurves/com.thoughtworks.xstream/bin/src/com/thoughtworks/xstream/mapper/DynamicProxyMapper.java
//

#ifndef _ComThoughtworksXstreamMapperDynamicProxyMapper_H_
#define _ComThoughtworksXstreamMapperDynamicProxyMapper_H_

#include "J2ObjC_header.h"
#include "com/thoughtworks/xstream/mapper/MapperWrapper.h"

@class IOSClass;
@protocol ComThoughtworksXstreamMapperMapper;

@interface ComThoughtworksXstreamMapperDynamicProxyMapper : ComThoughtworksXstreamMapperMapperWrapper

#pragma mark Public

- (instancetype)initWithComThoughtworksXstreamMapperMapper:(id<ComThoughtworksXstreamMapperMapper>)wrapped;

- (instancetype)initWithComThoughtworksXstreamMapperMapper:(id<ComThoughtworksXstreamMapperMapper>)wrapped
                                              withNSString:(NSString *)alias;

- (NSString *)getAlias;

- (IOSClass *)realClassWithNSString:(NSString *)elementName;

- (NSString *)serializedClassWithIOSClass:(IOSClass *)type;

- (void)setAliasWithNSString:(NSString *)alias;

@end

J2OBJC_EMPTY_STATIC_INIT(ComThoughtworksXstreamMapperDynamicProxyMapper)

FOUNDATION_EXPORT void ComThoughtworksXstreamMapperDynamicProxyMapper_initWithComThoughtworksXstreamMapperMapper_(ComThoughtworksXstreamMapperDynamicProxyMapper *self, id<ComThoughtworksXstreamMapperMapper> wrapped);

FOUNDATION_EXPORT ComThoughtworksXstreamMapperDynamicProxyMapper *new_ComThoughtworksXstreamMapperDynamicProxyMapper_initWithComThoughtworksXstreamMapperMapper_(id<ComThoughtworksXstreamMapperMapper> wrapped) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT void ComThoughtworksXstreamMapperDynamicProxyMapper_initWithComThoughtworksXstreamMapperMapper_withNSString_(ComThoughtworksXstreamMapperDynamicProxyMapper *self, id<ComThoughtworksXstreamMapperMapper> wrapped, NSString *alias);

FOUNDATION_EXPORT ComThoughtworksXstreamMapperDynamicProxyMapper *new_ComThoughtworksXstreamMapperDynamicProxyMapper_initWithComThoughtworksXstreamMapperMapper_withNSString_(id<ComThoughtworksXstreamMapperMapper> wrapped, NSString *alias) NS_RETURNS_RETAINED;

J2OBJC_TYPE_LITERAL_HEADER(ComThoughtworksXstreamMapperDynamicProxyMapper)

@interface ComThoughtworksXstreamMapperDynamicProxyMapper_DynamicProxy : NSObject

#pragma mark Public

- (instancetype)init;

@end

J2OBJC_EMPTY_STATIC_INIT(ComThoughtworksXstreamMapperDynamicProxyMapper_DynamicProxy)

FOUNDATION_EXPORT void ComThoughtworksXstreamMapperDynamicProxyMapper_DynamicProxy_init(ComThoughtworksXstreamMapperDynamicProxyMapper_DynamicProxy *self);

FOUNDATION_EXPORT ComThoughtworksXstreamMapperDynamicProxyMapper_DynamicProxy *new_ComThoughtworksXstreamMapperDynamicProxyMapper_DynamicProxy_init() NS_RETURNS_RETAINED;

J2OBJC_TYPE_LITERAL_HEADER(ComThoughtworksXstreamMapperDynamicProxyMapper_DynamicProxy)

#endif // _ComThoughtworksXstreamMapperDynamicProxyMapper_H_
