//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/Zetzsche/Development/SimarisCurves/com.thoughtworks.xstream/bin/src/com/thoughtworks/xstream/mapper/FieldAliasingMapper.java
//


#line 1 "/Users/Zetzsche/Development/SimarisCurves/com.thoughtworks.xstream/bin/src/com/thoughtworks/xstream/mapper/FieldAliasingMapper.java"

#include "IOSClass.h"
#include "J2ObjC_source.h"
#include "com/thoughtworks/xstream/core/util/FastField.h"
#include "com/thoughtworks/xstream/mapper/FieldAliasingMapper.h"
#include "com/thoughtworks/xstream/mapper/Mapper.h"
#include "com/thoughtworks/xstream/mapper/MapperWrapper.h"
#include "java/util/HashMap.h"
#include "java/util/HashSet.h"
#include "java/util/Iterator.h"
#include "java/util/LinkedHashSet.h"
#include "java/util/Map.h"
#include "java/util/Set.h"
#include "java/util/regex/Matcher.h"
#include "java/util/regex/Pattern.h"

@interface ComThoughtworksXstreamMapperFieldAliasingMapper ()

- (id)keyWithIOSClass:(IOSClass *)type
         withNSString:(NSString *)name;

- (NSString *)getMemberWithIOSClass:(IOSClass *)type
                       withNSString:(NSString *)name
                    withJavaUtilMap:(id<JavaUtilMap>)map;

@end

__attribute__((unused)) static id ComThoughtworksXstreamMapperFieldAliasingMapper_keyWithIOSClass_withNSString_(ComThoughtworksXstreamMapperFieldAliasingMapper *self, IOSClass *type, NSString *name);

__attribute__((unused)) static NSString *ComThoughtworksXstreamMapperFieldAliasingMapper_getMemberWithIOSClass_withNSString_withJavaUtilMap_(ComThoughtworksXstreamMapperFieldAliasingMapper *self, IOSClass *type, NSString *name, id<JavaUtilMap> map);


#line 30
@implementation ComThoughtworksXstreamMapperFieldAliasingMapper


#line 37
- (instancetype)initWithComThoughtworksXstreamMapperMapper:(id<ComThoughtworksXstreamMapperMapper>)wrapped {
  ComThoughtworksXstreamMapperFieldAliasingMapper_initWithComThoughtworksXstreamMapperMapper_(self, wrapped);
  return self;
}


#line 41
- (void)addFieldAliasWithNSString:(NSString *)alias
                     withIOSClass:(IOSClass *)type
                     withNSString:(NSString *)fieldName {
  (void) [((id<JavaUtilMap>) nil_chk(fieldToAliasMap_)) putWithId:ComThoughtworksXstreamMapperFieldAliasingMapper_keyWithIOSClass_withNSString_(self, type, fieldName) withId:alias];
  (void) [((id<JavaUtilMap>) nil_chk(aliasToFieldMap_)) putWithId:ComThoughtworksXstreamMapperFieldAliasingMapper_keyWithIOSClass_withNSString_(self, type, alias) withId:fieldName];
}


#line 46
- (void)addFieldsToIgnoreWithJavaUtilRegexPattern:(JavaUtilRegexPattern *)pattern {
  [((id<JavaUtilSet>) nil_chk(unknownFieldsToIgnore_)) addWithId:pattern];
}

- (id)keyWithIOSClass:(IOSClass *)type
         withNSString:(NSString *)name {
  return ComThoughtworksXstreamMapperFieldAliasingMapper_keyWithIOSClass_withNSString_(self, type, name);
}


#line 54
- (NSString *)serializedMemberWithIOSClass:(IOSClass *)type
                              withNSString:(NSString *)memberName {
  NSString *alias = ComThoughtworksXstreamMapperFieldAliasingMapper_getMemberWithIOSClass_withNSString_withJavaUtilMap_(self, type, memberName, fieldToAliasMap_);
  if (alias == nil) {
    return [super serializedMemberWithIOSClass:type withNSString:memberName];
  }
  else {
    
#line 59
    return alias;
  }
}


#line 63
- (NSString *)realMemberWithIOSClass:(IOSClass *)type
                        withNSString:(NSString *)serialized {
  NSString *real = ComThoughtworksXstreamMapperFieldAliasingMapper_getMemberWithIOSClass_withNSString_withJavaUtilMap_(self, type, serialized, aliasToFieldMap_);
  if (real == nil) {
    return [super realMemberWithIOSClass:type withNSString:serialized];
  }
  else {
    
#line 68
    return real;
  }
}


#line 72
- (NSString *)getMemberWithIOSClass:(IOSClass *)type
                       withNSString:(NSString *)name
                    withJavaUtilMap:(id<JavaUtilMap>)map {
  return ComThoughtworksXstreamMapperFieldAliasingMapper_getMemberWithIOSClass_withNSString_withJavaUtilMap_(self, type, name, map);
}


#line 82
- (jboolean)shouldSerializeMemberWithIOSClass:(IOSClass *)definedIn
                                 withNSString:(NSString *)fieldName {
  if ([((id<JavaUtilSet>) nil_chk(fieldsToOmit_)) containsWithId:ComThoughtworksXstreamMapperFieldAliasingMapper_keyWithIOSClass_withNSString_(self, definedIn, fieldName)]) {
    return NO;
  }
  else
#line 85
  if (definedIn == NSObject_class_() && ![((id<JavaUtilSet>) nil_chk(unknownFieldsToIgnore_)) isEmpty]) {
    for (id<JavaUtilIterator> iter = [unknownFieldsToIgnore_ iterator]; [((id<JavaUtilIterator>) nil_chk(iter)) hasNext]; ) {
      JavaUtilRegexPattern *pattern = (JavaUtilRegexPattern *) check_class_cast([iter next], [JavaUtilRegexPattern class]);
      if ([((JavaUtilRegexMatcher *) nil_chk([((JavaUtilRegexPattern *) nil_chk(pattern)) matcherWithJavaLangCharSequence:fieldName])) matches]) {
        return NO;
      }
    }
  }
  return YES;
}


#line 96
- (void)omitFieldWithIOSClass:(IOSClass *)definedIn
                 withNSString:(NSString *)fieldName {
  [((id<JavaUtilSet>) nil_chk(fieldsToOmit_)) addWithId:ComThoughtworksXstreamMapperFieldAliasingMapper_keyWithIOSClass_withNSString_(self, definedIn, fieldName)];
}

+ (const J2ObjcClassInfo *)__metadata {
  static const J2ObjcMethodInfo methods[] = {
    { "initWithComThoughtworksXstreamMapperMapper:", "FieldAliasingMapper", NULL, 0x1, NULL, NULL },
    { "addFieldAliasWithNSString:withIOSClass:withNSString:", "addFieldAlias", "V", 0x1, NULL, NULL },
    { "addFieldsToIgnoreWithJavaUtilRegexPattern:", "addFieldsToIgnore", "V", 0x1, NULL, NULL },
    { "keyWithIOSClass:withNSString:", "key", "Ljava.lang.Object;", 0x2, NULL, NULL },
    { "serializedMemberWithIOSClass:withNSString:", "serializedMember", "Ljava.lang.String;", 0x1, NULL, NULL },
    { "realMemberWithIOSClass:withNSString:", "realMember", "Ljava.lang.String;", 0x1, NULL, NULL },
    { "getMemberWithIOSClass:withNSString:withJavaUtilMap:", "getMember", "Ljava.lang.String;", 0x2, NULL, NULL },
    { "shouldSerializeMemberWithIOSClass:withNSString:", "shouldSerializeMember", "Z", 0x1, NULL, NULL },
    { "omitFieldWithIOSClass:withNSString:", "omitField", "V", 0x1, NULL, NULL },
  };
  static const J2ObjcFieldInfo fields[] = {
    { "fieldToAliasMap_", NULL, 0x14, "Ljava.util.Map;", NULL, NULL,  },
    { "aliasToFieldMap_", NULL, 0x14, "Ljava.util.Map;", NULL, NULL,  },
    { "fieldsToOmit_", NULL, 0x14, "Ljava.util.Set;", NULL, NULL,  },
    { "unknownFieldsToIgnore_", NULL, 0x14, "Ljava.util.Set;", NULL, NULL,  },
  };
  static const J2ObjcClassInfo _ComThoughtworksXstreamMapperFieldAliasingMapper = { 2, "FieldAliasingMapper", "com.thoughtworks.xstream.mapper", NULL, 0x1, 9, methods, 4, fields, 0, NULL, 0, NULL, NULL, NULL };
  return &_ComThoughtworksXstreamMapperFieldAliasingMapper;
}

@end


#line 37
void ComThoughtworksXstreamMapperFieldAliasingMapper_initWithComThoughtworksXstreamMapperMapper_(ComThoughtworksXstreamMapperFieldAliasingMapper *self, id<ComThoughtworksXstreamMapperMapper> wrapped) {
  (void) ComThoughtworksXstreamMapperMapperWrapper_initWithComThoughtworksXstreamMapperMapper_(self, wrapped);
  self->fieldToAliasMap_ = new_JavaUtilHashMap_init();
  self->aliasToFieldMap_ = new_JavaUtilHashMap_init();
  self->fieldsToOmit_ = new_JavaUtilHashSet_init();
  self->unknownFieldsToIgnore_ = new_JavaUtilLinkedHashSet_init();
}


#line 37
ComThoughtworksXstreamMapperFieldAliasingMapper *new_ComThoughtworksXstreamMapperFieldAliasingMapper_initWithComThoughtworksXstreamMapperMapper_(id<ComThoughtworksXstreamMapperMapper> wrapped) {
  ComThoughtworksXstreamMapperFieldAliasingMapper *self = [ComThoughtworksXstreamMapperFieldAliasingMapper alloc];
  ComThoughtworksXstreamMapperFieldAliasingMapper_initWithComThoughtworksXstreamMapperMapper_(self, wrapped);
  return self;
}


#line 50
id ComThoughtworksXstreamMapperFieldAliasingMapper_keyWithIOSClass_withNSString_(ComThoughtworksXstreamMapperFieldAliasingMapper *self, IOSClass *type, NSString *name) {
  return new_ComThoughtworksXstreamCoreUtilFastField_initWithIOSClass_withNSString_(type, name);
}


#line 72
NSString *ComThoughtworksXstreamMapperFieldAliasingMapper_getMemberWithIOSClass_withNSString_withJavaUtilMap_(ComThoughtworksXstreamMapperFieldAliasingMapper *self, IOSClass *type, NSString *name, id<JavaUtilMap> map) {
  NSString *member = nil;
  for (IOSClass *declaringType = type;
#line 75
  member == nil && declaringType != NSObject_class_() && declaringType != nil;
#line 76
  declaringType = [((IOSClass *) nil_chk(declaringType)) getSuperclass]) {
    member = (NSString *) check_class_cast([((id<JavaUtilMap>) nil_chk(map)) getWithId:ComThoughtworksXstreamMapperFieldAliasingMapper_keyWithIOSClass_withNSString_(self, declaringType, name)], [NSString class]);
  }
  return member;
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(ComThoughtworksXstreamMapperFieldAliasingMapper)
