//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/Zetzsche/Development/SimarisCurves/com.thoughtworks.xstream/src/com/thoughtworks/xstream/mapper/XmlFriendlyMapper.java
//

#line 1 "/Users/Zetzsche/Development/SimarisCurves/com.thoughtworks.xstream/src/com/thoughtworks/xstream/mapper/XmlFriendlyMapper.java"

#include "IOSClass.h"
#include "com/thoughtworks/xstream/mapper/AbstractXmlFriendlyMapper.h"
#include "com/thoughtworks/xstream/mapper/Mapper.h"
#include "com/thoughtworks/xstream/mapper/XmlFriendlyMapper.h"


#line 28
@implementation ComThoughtworksXstreamMapperXmlFriendlyMapper


#line 33
- (instancetype)initWithComThoughtworksXstreamMapperMapper:(id<ComThoughtworksXstreamMapperMapper>)wrapped {
  return
#line 34
  [super initWithComThoughtworksXstreamMapperMapper:wrapped];
}


#line 37
- (NSString *)serializedClassWithIOSClass:(IOSClass *)type {
  
#line 38
  return [self escapeClassNameWithNSString:[super serializedClassWithIOSClass:type]];
}


#line 41
- (IOSClass *)realClassWithNSString:(NSString *)elementName {
  
#line 42
  return [super realClassWithNSString:[self unescapeClassNameWithNSString:elementName]];
}


#line 45
- (NSString *)serializedMemberWithIOSClass:(IOSClass *)type
                              withNSString:(NSString *)memberName {
  
#line 46
  return [self escapeFieldNameWithNSString:[super serializedMemberWithIOSClass:type withNSString:memberName]];
}


#line 49
- (NSString *)realMemberWithIOSClass:(IOSClass *)type
                        withNSString:(NSString *)serialized {
  
#line 50
  return [self unescapeFieldNameWithNSString:[super realMemberWithIOSClass:type withNSString:serialized]];
}


#line 53
- (NSString *)mapNameToXMLWithNSString:(NSString *)javaName {
  
#line 54
  return [self escapeFieldNameWithNSString:javaName];
}


#line 57
- (NSString *)mapNameFromXMLWithNSString:(NSString *)xmlName {
  
#line 58
  return [self unescapeFieldNameWithNSString:xmlName];
}

+ (const J2ObjcClassInfo *)__metadata {
  static const J2ObjcMethodInfo methods[] = {
    { "initWithComThoughtworksXstreamMapperMapper:", "XmlFriendlyMapper", NULL, 0x1, NULL },
    { "serializedClassWithIOSClass:", "serializedClass", "Ljava.lang.String;", 0x1, NULL },
    { "realClassWithNSString:", "realClass", "Ljava.lang.Class;", 0x1, NULL },
    { "serializedMemberWithIOSClass:withNSString:", "serializedMember", "Ljava.lang.String;", 0x1, NULL },
    { "realMemberWithIOSClass:withNSString:", "realMember", "Ljava.lang.String;", 0x1, NULL },
    { "mapNameToXMLWithNSString:", "mapNameToXML", "Ljava.lang.String;", 0x1, NULL },
    { "mapNameFromXMLWithNSString:", "mapNameFromXML", "Ljava.lang.String;", 0x1, NULL },
  };
  static const J2ObjcClassInfo _ComThoughtworksXstreamMapperXmlFriendlyMapper = { "XmlFriendlyMapper", "com.thoughtworks.xstream.mapper", NULL, 0x1, 7, methods, 0, NULL, 0, NULL};
  return &_ComThoughtworksXstreamMapperXmlFriendlyMapper;
}

@end
