//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/Zetzsche/Development/SimarisCurves/com.thoughtworks.xstream/bin/src/com/thoughtworks/xstream/mapper/XStream11XmlFriendlyMapper.java
//


#line 1 "/Users/Zetzsche/Development/SimarisCurves/com.thoughtworks.xstream/bin/src/com/thoughtworks/xstream/mapper/XStream11XmlFriendlyMapper.java"

#include "IOSClass.h"
#include "J2ObjC_source.h"
#include "com/thoughtworks/xstream/mapper/AbstractXmlFriendlyMapper.h"
#include "com/thoughtworks/xstream/mapper/Mapper.h"
#include "com/thoughtworks/xstream/mapper/XStream11XmlFriendlyMapper.h"


#line 31
@implementation ComThoughtworksXstreamMapperXStream11XmlFriendlyMapper

- (instancetype)initWithComThoughtworksXstreamMapperMapper:(id<ComThoughtworksXstreamMapperMapper>)wrapped {
  ComThoughtworksXstreamMapperXStream11XmlFriendlyMapper_initWithComThoughtworksXstreamMapperMapper_(self, wrapped);
  return self;
}


#line 37
- (IOSClass *)realClassWithNSString:(NSString *)elementName {
  return [super realClassWithNSString:[self unescapeClassNameWithNSString:elementName]];
}

- (NSString *)realMemberWithIOSClass:(IOSClass *)type
                        withNSString:(NSString *)serialized {
  return [self unescapeFieldNameWithNSString:[super realMemberWithIOSClass:type withNSString:serialized]];
}


#line 45
- (NSString *)mapNameFromXMLWithNSString:(NSString *)xmlName {
  return [self unescapeFieldNameWithNSString:xmlName];
}

+ (const J2ObjcClassInfo *)__metadata {
  static const J2ObjcMethodInfo methods[] = {
    { "initWithComThoughtworksXstreamMapperMapper:", "XStream11XmlFriendlyMapper", NULL, 0x1, NULL, NULL },
    { "realClassWithNSString:", "realClass", "Ljava.lang.Class;", 0x1, NULL, NULL },
    { "realMemberWithIOSClass:withNSString:", "realMember", "Ljava.lang.String;", 0x1, NULL, NULL },
    { "mapNameFromXMLWithNSString:", "mapNameFromXML", "Ljava.lang.String;", 0x1, NULL, NULL },
  };
  static const J2ObjcClassInfo _ComThoughtworksXstreamMapperXStream11XmlFriendlyMapper = { 2, "XStream11XmlFriendlyMapper", "com.thoughtworks.xstream.mapper", NULL, 0x1, 4, methods, 0, NULL, 0, NULL, 0, NULL, NULL, NULL };
  return &_ComThoughtworksXstreamMapperXStream11XmlFriendlyMapper;
}

@end


#line 33
void ComThoughtworksXstreamMapperXStream11XmlFriendlyMapper_initWithComThoughtworksXstreamMapperMapper_(ComThoughtworksXstreamMapperXStream11XmlFriendlyMapper *self, id<ComThoughtworksXstreamMapperMapper> wrapped) {
  (void) ComThoughtworksXstreamMapperAbstractXmlFriendlyMapper_initWithComThoughtworksXstreamMapperMapper_(self, wrapped);
}


#line 33
ComThoughtworksXstreamMapperXStream11XmlFriendlyMapper *new_ComThoughtworksXstreamMapperXStream11XmlFriendlyMapper_initWithComThoughtworksXstreamMapperMapper_(id<ComThoughtworksXstreamMapperMapper> wrapped) {
  ComThoughtworksXstreamMapperXStream11XmlFriendlyMapper *self = [ComThoughtworksXstreamMapperXStream11XmlFriendlyMapper alloc];
  ComThoughtworksXstreamMapperXStream11XmlFriendlyMapper_initWithComThoughtworksXstreamMapperMapper_(self, wrapped);
  return self;
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(ComThoughtworksXstreamMapperXStream11XmlFriendlyMapper)
