//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/Zetzsche/Development/SimarisCurves/com.thoughtworks.xstream/src/com/thoughtworks/xstream/io/xml/xppdom/Xpp3DomBuilder.java
//

#ifndef _ComThoughtworksXstreamIoXmlXppdomXpp3DomBuilder_H_
#define _ComThoughtworksXstreamIoXmlXppdomXpp3DomBuilder_H_

@class ComThoughtworksXstreamIoXmlXppdomXpp3Dom;
@class JavaIoReader;

#import "JreEmulation.h"

@interface ComThoughtworksXstreamIoXmlXppdomXpp3DomBuilder : NSObject {
}

+ (ComThoughtworksXstreamIoXmlXppdomXpp3Dom *)buildWithJavaIoReader:(JavaIoReader *)reader;

- (instancetype)init;

@end

__attribute__((always_inline)) inline void ComThoughtworksXstreamIoXmlXppdomXpp3DomBuilder_init() {}

#endif // _ComThoughtworksXstreamIoXmlXppdomXpp3DomBuilder_H_
