//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/Zetzsche/Development/SimarisCurves/com.thoughtworks.xstream/bin/src/com/thoughtworks/xstream/io/xml/xppdom/XppDom.java
//

#ifndef _ComThoughtworksXstreamIoXmlXppdomXppDom_H_
#define _ComThoughtworksXstreamIoXmlXppdomXppDom_H_

#include "J2ObjC_header.h"
#include "java/io/Serializable.h"

@class IOSObjectArray;
@protocol OrgXmlpullV1XmlPullParser;

@interface ComThoughtworksXstreamIoXmlXppdomXppDom : NSObject < JavaIoSerializable >

#pragma mark Public

- (instancetype)initWithNSString:(NSString *)name;

- (void)addChildWithComThoughtworksXstreamIoXmlXppdomXppDom:(ComThoughtworksXstreamIoXmlXppdomXppDom *)xpp3Dom;

+ (ComThoughtworksXstreamIoXmlXppdomXppDom *)buildWithOrgXmlpullV1XmlPullParser:(id<OrgXmlpullV1XmlPullParser>)parser;

- (NSString *)getAttributeWithNSString:(NSString *)name;

- (IOSObjectArray *)getAttributeNames;

- (ComThoughtworksXstreamIoXmlXppdomXppDom *)getChildWithInt:(jint)i;

- (ComThoughtworksXstreamIoXmlXppdomXppDom *)getChildWithNSString:(NSString *)name;

- (jint)getChildCount;

- (IOSObjectArray *)getChildren;

- (IOSObjectArray *)getChildrenWithNSString:(NSString *)name;

- (NSString *)getName;

- (ComThoughtworksXstreamIoXmlXppdomXppDom *)getParent;

- (NSString *)getValue;

- (void)setAttributeWithNSString:(NSString *)name
                    withNSString:(NSString *)value;

- (void)setParentWithComThoughtworksXstreamIoXmlXppdomXppDom:(ComThoughtworksXstreamIoXmlXppdomXppDom *)parent;

- (void)setValueWithNSString:(NSString *)value;

#pragma mark Package-Private

- (id)readResolve;

@end

J2OBJC_EMPTY_STATIC_INIT(ComThoughtworksXstreamIoXmlXppdomXppDom)

FOUNDATION_EXPORT void ComThoughtworksXstreamIoXmlXppdomXppDom_initWithNSString_(ComThoughtworksXstreamIoXmlXppdomXppDom *self, NSString *name);

FOUNDATION_EXPORT ComThoughtworksXstreamIoXmlXppdomXppDom *new_ComThoughtworksXstreamIoXmlXppdomXppDom_initWithNSString_(NSString *name) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ComThoughtworksXstreamIoXmlXppdomXppDom *ComThoughtworksXstreamIoXmlXppdomXppDom_buildWithOrgXmlpullV1XmlPullParser_(id<OrgXmlpullV1XmlPullParser> parser);

J2OBJC_TYPE_LITERAL_HEADER(ComThoughtworksXstreamIoXmlXppdomXppDom)

#endif // _ComThoughtworksXstreamIoXmlXppdomXppDom_H_
