//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/Zetzsche/Development/SimarisCurves/com.thoughtworks.xstream/bin/src/com/thoughtworks/xstream/io/xml/xppdom/XppFactory.java
//

#ifndef _ComThoughtworksXstreamIoXmlXppdomXppFactory_H_
#define _ComThoughtworksXstreamIoXmlXppdomXppFactory_H_

#include "J2ObjC_header.h"

@class ComThoughtworksXstreamIoXmlXppdomXppDom;
@class JavaIoInputStream;
@class JavaIoReader;
@protocol OrgXmlpullV1XmlPullParser;

@interface ComThoughtworksXstreamIoXmlXppdomXppFactory : NSObject

#pragma mark Public

- (instancetype)init;

+ (ComThoughtworksXstreamIoXmlXppdomXppDom *)buildDomWithJavaIoInputStream:(JavaIoInputStream *)inArg
                                                              withNSString:(NSString *)encoding;

+ (ComThoughtworksXstreamIoXmlXppdomXppDom *)buildDomWithJavaIoReader:(JavaIoReader *)r;

+ (ComThoughtworksXstreamIoXmlXppdomXppDom *)buildDomWithNSString:(NSString *)xml;

+ (id<OrgXmlpullV1XmlPullParser>)createDefaultParser;

@end

J2OBJC_EMPTY_STATIC_INIT(ComThoughtworksXstreamIoXmlXppdomXppFactory)

FOUNDATION_EXPORT id<OrgXmlpullV1XmlPullParser> ComThoughtworksXstreamIoXmlXppdomXppFactory_createDefaultParser();

FOUNDATION_EXPORT ComThoughtworksXstreamIoXmlXppdomXppDom *ComThoughtworksXstreamIoXmlXppdomXppFactory_buildDomWithNSString_(NSString *xml);

FOUNDATION_EXPORT ComThoughtworksXstreamIoXmlXppdomXppDom *ComThoughtworksXstreamIoXmlXppdomXppFactory_buildDomWithJavaIoReader_(JavaIoReader *r);

FOUNDATION_EXPORT ComThoughtworksXstreamIoXmlXppdomXppDom *ComThoughtworksXstreamIoXmlXppdomXppFactory_buildDomWithJavaIoInputStream_withNSString_(JavaIoInputStream *inArg, NSString *encoding);

FOUNDATION_EXPORT void ComThoughtworksXstreamIoXmlXppdomXppFactory_init(ComThoughtworksXstreamIoXmlXppdomXppFactory *self);

FOUNDATION_EXPORT ComThoughtworksXstreamIoXmlXppdomXppFactory *new_ComThoughtworksXstreamIoXmlXppdomXppFactory_init() NS_RETURNS_RETAINED;

J2OBJC_TYPE_LITERAL_HEADER(ComThoughtworksXstreamIoXmlXppdomXppFactory)

#endif // _ComThoughtworksXstreamIoXmlXppdomXppFactory_H_
