//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/Zetzsche/Development/SimarisCurves/com.thoughtworks.xstream/bin/src/com/thoughtworks/xstream/io/binary/ReaderDepthState.java
//

#ifndef _ComThoughtworksXstreamIoBinaryReaderDepthState_H_
#define _ComThoughtworksXstreamIoBinaryReaderDepthState_H_

#include "J2ObjC_header.h"

@protocol JavaUtilIterator;

@interface ComThoughtworksXstreamIoBinaryReaderDepthState : NSObject

#pragma mark Public

- (void)addAttributeWithNSString:(NSString *)name
                    withNSString:(NSString *)value;

- (NSString *)getAttributeWithInt:(jint)index;

- (NSString *)getAttributeWithNSString:(NSString *)name;

- (jint)getAttributeCount;

- (NSString *)getAttributeNameWithInt:(jint)index;

- (id<JavaUtilIterator>)getAttributeNames;

- (NSString *)getName;

- (NSString *)getValue;

- (jboolean)hasMoreChildren;

- (void)pop;

- (void)push;

- (void)setHasMoreChildrenWithBoolean:(jboolean)hasMoreChildren;

- (void)setNameWithNSString:(NSString *)name;

- (void)setValueWithNSString:(NSString *)value;

#pragma mark Package-Private

- (instancetype)init;

@end

J2OBJC_EMPTY_STATIC_INIT(ComThoughtworksXstreamIoBinaryReaderDepthState)

FOUNDATION_EXPORT void ComThoughtworksXstreamIoBinaryReaderDepthState_init(ComThoughtworksXstreamIoBinaryReaderDepthState *self);

FOUNDATION_EXPORT ComThoughtworksXstreamIoBinaryReaderDepthState *new_ComThoughtworksXstreamIoBinaryReaderDepthState_init() NS_RETURNS_RETAINED;

J2OBJC_TYPE_LITERAL_HEADER(ComThoughtworksXstreamIoBinaryReaderDepthState)

#endif // _ComThoughtworksXstreamIoBinaryReaderDepthState_H_
