//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/Zetzsche/Development/SimarisCurves/com.thoughtworks.xstream/gen/com/thoughtworks/xstream/R.java
//


#line 1 "/Users/Zetzsche/Development/SimarisCurves/com.thoughtworks.xstream/gen/com/thoughtworks/xstream/R.java"

#include "J2ObjC_source.h"
#include "com/thoughtworks/xstream/R.h"


#line 10
@implementation ComThoughtworksXstreamR

- (instancetype)init {
  ComThoughtworksXstreamR_init(self);
  return self;
}

+ (const J2ObjcClassInfo *)__metadata {
  static const J2ObjcMethodInfo methods[] = {
    { "init", NULL, NULL, 0x1, NULL, NULL },
  };
  static const char *inner_classes[] = {"Lcom.thoughtworks.xstream.R$attr;", "Lcom.thoughtworks.xstream.R$drawable;", "Lcom.thoughtworks.xstream.R$string;", "Lcom.thoughtworks.xstream.R$style;"};
  static const J2ObjcClassInfo _ComThoughtworksXstreamR = { 2, "R", "com.thoughtworks.xstream", NULL, 0x11, 1, methods, 0, NULL, 0, NULL, 4, inner_classes, NULL, NULL };
  return &_ComThoughtworksXstreamR;
}

@end

void ComThoughtworksXstreamR_init(ComThoughtworksXstreamR *self) {
  (void) NSObject_init(self);
}

ComThoughtworksXstreamR *new_ComThoughtworksXstreamR_init() {
  ComThoughtworksXstreamR *self = [ComThoughtworksXstreamR alloc];
  ComThoughtworksXstreamR_init(self);
  return self;
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(ComThoughtworksXstreamR)


#line 11
@implementation ComThoughtworksXstreamR_attr

- (instancetype)init {
  ComThoughtworksXstreamR_attr_init(self);
  return self;
}

+ (const J2ObjcClassInfo *)__metadata {
  static const J2ObjcMethodInfo methods[] = {
    { "init", NULL, NULL, 0x1, NULL, NULL },
  };
  static const J2ObjcClassInfo _ComThoughtworksXstreamR_attr = { 2, "attr", "com.thoughtworks.xstream", "R", 0x19, 1, methods, 0, NULL, 0, NULL, 0, NULL, NULL, NULL };
  return &_ComThoughtworksXstreamR_attr;
}

@end

void ComThoughtworksXstreamR_attr_init(ComThoughtworksXstreamR_attr *self) {
  (void) NSObject_init(self);
}

ComThoughtworksXstreamR_attr *new_ComThoughtworksXstreamR_attr_init() {
  ComThoughtworksXstreamR_attr *self = [ComThoughtworksXstreamR_attr alloc];
  ComThoughtworksXstreamR_attr_init(self);
  return self;
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(ComThoughtworksXstreamR_attr)

jint ComThoughtworksXstreamR_drawable_ic_launcher_ = 
#line 14
(jint) 0x7f020000;


#line 13
@implementation ComThoughtworksXstreamR_drawable

- (instancetype)init {
  ComThoughtworksXstreamR_drawable_init(self);
  return self;
}

+ (const J2ObjcClassInfo *)__metadata {
  static const J2ObjcMethodInfo methods[] = {
    { "init", NULL, NULL, 0x1, NULL, NULL },
  };
  static const J2ObjcFieldInfo fields[] = {
    { "ic_launcher_", NULL, 0x9, "I", &ComThoughtworksXstreamR_drawable_ic_launcher_, NULL,  },
  };
  static const J2ObjcClassInfo _ComThoughtworksXstreamR_drawable = { 2, "drawable", "com.thoughtworks.xstream", "R", 0x19, 1, methods, 1, fields, 0, NULL, 0, NULL, NULL, NULL };
  return &_ComThoughtworksXstreamR_drawable;
}

@end

void ComThoughtworksXstreamR_drawable_init(ComThoughtworksXstreamR_drawable *self) {
  (void) NSObject_init(self);
}

ComThoughtworksXstreamR_drawable *new_ComThoughtworksXstreamR_drawable_init() {
  ComThoughtworksXstreamR_drawable *self = [ComThoughtworksXstreamR_drawable alloc];
  ComThoughtworksXstreamR_drawable_init(self);
  return self;
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(ComThoughtworksXstreamR_drawable)

jint ComThoughtworksXstreamR_string_app_name_ = 
#line 17
(jint) 0x7f030000;


#line 16
@implementation ComThoughtworksXstreamR_string

- (instancetype)init {
  ComThoughtworksXstreamR_string_init(self);
  return self;
}

+ (const J2ObjcClassInfo *)__metadata {
  static const J2ObjcMethodInfo methods[] = {
    { "init", NULL, NULL, 0x1, NULL, NULL },
  };
  static const J2ObjcFieldInfo fields[] = {
    { "app_name_", NULL, 0x9, "I", &ComThoughtworksXstreamR_string_app_name_, NULL,  },
  };
  static const J2ObjcClassInfo _ComThoughtworksXstreamR_string = { 2, "string", "com.thoughtworks.xstream", "R", 0x19, 1, methods, 1, fields, 0, NULL, 0, NULL, NULL, NULL };
  return &_ComThoughtworksXstreamR_string;
}

@end

void ComThoughtworksXstreamR_string_init(ComThoughtworksXstreamR_string *self) {
  (void) NSObject_init(self);
}

ComThoughtworksXstreamR_string *new_ComThoughtworksXstreamR_string_init() {
  ComThoughtworksXstreamR_string *self = [ComThoughtworksXstreamR_string alloc];
  ComThoughtworksXstreamR_string_init(self);
  return self;
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(ComThoughtworksXstreamR_string)

jint ComThoughtworksXstreamR_style_AppBaseTheme_ = 
#line 41
(jint) 0x7f040000;
jint ComThoughtworksXstreamR_style_AppTheme_ = 
#line 45
(jint) 0x7f040001;


#line 19
@implementation ComThoughtworksXstreamR_style

- (instancetype)init {
  ComThoughtworksXstreamR_style_init(self);
  return self;
}

+ (const J2ObjcClassInfo *)__metadata {
  static const J2ObjcMethodInfo methods[] = {
    { "init", NULL, NULL, 0x1, NULL, NULL },
  };
  static const J2ObjcFieldInfo fields[] = {
    { "AppBaseTheme_", NULL, 0x9, "I", &ComThoughtworksXstreamR_style_AppBaseTheme_, NULL,  },
    { "AppTheme_", NULL, 0x9, "I", &ComThoughtworksXstreamR_style_AppTheme_, NULL,  },
  };
  static const J2ObjcClassInfo _ComThoughtworksXstreamR_style = { 2, "style", "com.thoughtworks.xstream", "R", 0x19, 1, methods, 2, fields, 0, NULL, 0, NULL, NULL, NULL };
  return &_ComThoughtworksXstreamR_style;
}

@end

void ComThoughtworksXstreamR_style_init(ComThoughtworksXstreamR_style *self) {
  (void) NSObject_init(self);
}

ComThoughtworksXstreamR_style *new_ComThoughtworksXstreamR_style_init() {
  ComThoughtworksXstreamR_style *self = [ComThoughtworksXstreamR_style alloc];
  ComThoughtworksXstreamR_style_init(self);
  return self;
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(ComThoughtworksXstreamR_style)
