//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/Zetzsche/Development/SimarisCurves/com.thoughtworks.xstream/src/com/thoughtworks/xstream/converters/ConverterLookup.java
//

#ifndef _ComThoughtworksXstreamConvertersConverterLookup_H_
#define _ComThoughtworksXstreamConvertersConverterLookup_H_

@class IOSClass;
@protocol ComThoughtworksXstreamConvertersConverter;

#import "JreEmulation.h"

@protocol ComThoughtworksXstreamConvertersConverterLookup < NSObject, JavaObject >

- (id<ComThoughtworksXstreamConvertersConverter>)lookupConverterForTypeWithIOSClass:(IOSClass *)type;

@end

__attribute__((always_inline)) inline void ComThoughtworksXstreamConvertersConverterLookup_init() {}

#endif // _ComThoughtworksXstreamConvertersConverterLookup_H_
