//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/Zetzsche/Development/SimarisCurves/com.thoughtworks.xstream/src/com/thoughtworks/xstream/converters/ConverterRegistry.java
//

#line 1 "/Users/Zetzsche/Development/SimarisCurves/com.thoughtworks.xstream/src/com/thoughtworks/xstream/converters/ConverterRegistry.java"

#include "com/thoughtworks/xstream/converters/Converter.h"
#include "com/thoughtworks/xstream/converters/ConverterRegistry.h"

@interface ComThoughtworksXstreamConvertersConverterRegistry : NSObject
@end

@implementation ComThoughtworksXstreamConvertersConverterRegistry

+ (const J2ObjcClassInfo *)__metadata {
  static const J2ObjcMethodInfo methods[] = {
    { "registerConverterWithComThoughtworksXstreamConvertersConverter:withInt:", "registerConverter", "V", 0x401, NULL },
  };
  static const J2ObjcClassInfo _ComThoughtworksXstreamConvertersConverterRegistry = { "ConverterRegistry", "com.thoughtworks.xstream.converters", NULL, 0x201, 1, methods, 0, NULL, 0, NULL};
  return &_ComThoughtworksXstreamConvertersConverterRegistry;
}

@end

