//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/Zetzsche/Development/SimarisCurves/com.thoughtworks.xstream/src/com/thoughtworks/xstream/converters/MarshallingContext.java
//

#line 1 "/Users/Zetzsche/Development/SimarisCurves/com.thoughtworks.xstream/src/com/thoughtworks/xstream/converters/MarshallingContext.java"

#include "com/thoughtworks/xstream/converters/Converter.h"
#include "com/thoughtworks/xstream/converters/MarshallingContext.h"

@interface ComThoughtworksXstreamConvertersMarshallingContext : NSObject
@end

@implementation ComThoughtworksXstreamConvertersMarshallingContext

+ (const J2ObjcClassInfo *)__metadata {
  static const J2ObjcMethodInfo methods[] = {
    { "convertAnotherWithId:", "convertAnother", "V", 0x401, NULL },
    { "convertAnotherWithId:withComThoughtworksXstreamConvertersConverter:", "convertAnother", "V", 0x401, NULL },
  };
  static const J2ObjcClassInfo _ComThoughtworksXstreamConvertersMarshallingContext = { "MarshallingContext", "com.thoughtworks.xstream.converters", NULL, 0x201, 2, methods, 0, NULL, 0, NULL};
  return &_ComThoughtworksXstreamConvertersMarshallingContext;
}

@end

