//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/Zetzsche/Development/SimarisCurves/com.thoughtworks.xstream/src/com/thoughtworks/xstream/converters/SingleValueConverterWrapper.java
//

#ifndef _ComThoughtworksXstreamConvertersSingleValueConverterWrapper_H_
#define _ComThoughtworksXstreamConvertersSingleValueConverterWrapper_H_

@class IOSClass;
@protocol ComThoughtworksXstreamConvertersErrorWriter;
@protocol ComThoughtworksXstreamConvertersMarshallingContext;
@protocol ComThoughtworksXstreamConvertersUnmarshallingContext;
@protocol ComThoughtworksXstreamIoHierarchicalStreamReader;
@protocol ComThoughtworksXstreamIoHierarchicalStreamWriter;

#import "JreEmulation.h"
#include "com/thoughtworks/xstream/converters/Converter.h"
#include "com/thoughtworks/xstream/converters/ErrorReporter.h"
#include "com/thoughtworks/xstream/converters/SingleValueConverter.h"

@interface ComThoughtworksXstreamConvertersSingleValueConverterWrapper : NSObject < ComThoughtworksXstreamConvertersConverter, ComThoughtworksXstreamConvertersSingleValueConverter, ComThoughtworksXstreamConvertersErrorReporter > {
 @public
  id<ComThoughtworksXstreamConvertersSingleValueConverter> wrapped_;
}

- (instancetype)initWithComThoughtworksXstreamConvertersSingleValueConverter:(id<ComThoughtworksXstreamConvertersSingleValueConverter>)wrapped;

- (jboolean)canConvertWithIOSClass:(IOSClass *)type;

- (NSString *)toStringWithId:(id)obj;

- (id)fromStringWithNSString:(NSString *)str;

- (void)marshalWithId:(id)source
withComThoughtworksXstreamIoHierarchicalStreamWriter:(id<ComThoughtworksXstreamIoHierarchicalStreamWriter>)writer
withComThoughtworksXstreamConvertersMarshallingContext:(id<ComThoughtworksXstreamConvertersMarshallingContext>)context;

- (id)unmarshalWithComThoughtworksXstreamIoHierarchicalStreamReader:(id<ComThoughtworksXstreamIoHierarchicalStreamReader>)reader
           withComThoughtworksXstreamConvertersUnmarshallingContext:(id<ComThoughtworksXstreamConvertersUnmarshallingContext>)context;

- (void)appendErrorsWithComThoughtworksXstreamConvertersErrorWriter:(id<ComThoughtworksXstreamConvertersErrorWriter>)errorWriter;

- (void)copyAllFieldsTo:(ComThoughtworksXstreamConvertersSingleValueConverterWrapper *)other;

@end

__attribute__((always_inline)) inline void ComThoughtworksXstreamConvertersSingleValueConverterWrapper_init() {}

J2OBJC_FIELD_SETTER(ComThoughtworksXstreamConvertersSingleValueConverterWrapper, wrapped_, id<ComThoughtworksXstreamConvertersSingleValueConverter>)

#endif // _ComThoughtworksXstreamConvertersSingleValueConverterWrapper_H_
