//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/Zetzsche/Development/SimarisCurves/com.thoughtworks.xstream/bin/src/com/thoughtworks/xstream/converters/SingleValueConverterWrapper.java
//


#line 1 "/Users/Zetzsche/Development/SimarisCurves/com.thoughtworks.xstream/bin/src/com/thoughtworks/xstream/converters/SingleValueConverterWrapper.java"

#include "IOSClass.h"
#include "J2ObjC_source.h"
#include "com/thoughtworks/xstream/converters/ErrorReporter.h"
#include "com/thoughtworks/xstream/converters/ErrorWriter.h"
#include "com/thoughtworks/xstream/converters/MarshallingContext.h"
#include "com/thoughtworks/xstream/converters/SingleValueConverter.h"
#include "com/thoughtworks/xstream/converters/SingleValueConverterWrapper.h"
#include "com/thoughtworks/xstream/converters/UnmarshallingContext.h"
#include "com/thoughtworks/xstream/io/HierarchicalStreamReader.h"
#include "com/thoughtworks/xstream/io/HierarchicalStreamWriter.h"

@interface ComThoughtworksXstreamConvertersSingleValueConverterWrapper () {
 @public
  id<ComThoughtworksXstreamConvertersSingleValueConverter> wrapped_;
}

@end

J2OBJC_FIELD_SETTER(ComThoughtworksXstreamConvertersSingleValueConverterWrapper, wrapped_, id<ComThoughtworksXstreamConvertersSingleValueConverter>)


#line 24
@implementation ComThoughtworksXstreamConvertersSingleValueConverterWrapper


#line 28
- (instancetype)initWithComThoughtworksXstreamConvertersSingleValueConverter:(id<ComThoughtworksXstreamConvertersSingleValueConverter>)wrapped {
  ComThoughtworksXstreamConvertersSingleValueConverterWrapper_initWithComThoughtworksXstreamConvertersSingleValueConverter_(self, wrapped);
  return self;
}


#line 32
- (jboolean)canConvertWithIOSClass:(IOSClass *)type {
  return [((id<ComThoughtworksXstreamConvertersSingleValueConverter>) nil_chk(wrapped_)) canConvertWithIOSClass:type];
}

- (NSString *)toStringWithId:(id)obj {
  return [((id<ComThoughtworksXstreamConvertersSingleValueConverter>) nil_chk(wrapped_)) toStringWithId:obj];
}

- (id)fromStringWithNSString:(NSString *)str {
  return [((id<ComThoughtworksXstreamConvertersSingleValueConverter>) nil_chk(wrapped_)) fromStringWithNSString:str];
}

- (void)marshalWithId:(id)source
withComThoughtworksXstreamIoHierarchicalStreamWriter:(id<ComThoughtworksXstreamIoHierarchicalStreamWriter>)writer
withComThoughtworksXstreamConvertersMarshallingContext:(id<ComThoughtworksXstreamConvertersMarshallingContext>)context {
  [((id<ComThoughtworksXstreamIoHierarchicalStreamWriter>) nil_chk(writer)) setValueWithNSString:[self toStringWithId:source]];
}


#line 48
- (id)unmarshalWithComThoughtworksXstreamIoHierarchicalStreamReader:(id<ComThoughtworksXstreamIoHierarchicalStreamReader>)reader
           withComThoughtworksXstreamConvertersUnmarshallingContext:(id<ComThoughtworksXstreamConvertersUnmarshallingContext>)context {
  return [self fromStringWithNSString:[((id<ComThoughtworksXstreamIoHierarchicalStreamReader>) nil_chk(reader)) getValue]];
}


#line 52
- (void)appendErrorsWithComThoughtworksXstreamConvertersErrorWriter:(id<ComThoughtworksXstreamConvertersErrorWriter>)errorWriter {
  [((id<ComThoughtworksXstreamConvertersErrorWriter>) nil_chk(errorWriter)) addWithNSString:@"wrapped-converter" withNSString:wrapped_ == nil ? @"(null)" : [[wrapped_ getClass] getName]];
  if ([ComThoughtworksXstreamConvertersErrorReporter_class_() isInstance:wrapped_]) {
    [((id<ComThoughtworksXstreamConvertersErrorReporter>) nil_chk(((id<ComThoughtworksXstreamConvertersErrorReporter>) check_protocol_cast(wrapped_, @protocol(ComThoughtworksXstreamConvertersErrorReporter))))) appendErrorsWithComThoughtworksXstreamConvertersErrorWriter:errorWriter];
  }
}

+ (const J2ObjcClassInfo *)__metadata {
  static const J2ObjcMethodInfo methods[] = {
    { "initWithComThoughtworksXstreamConvertersSingleValueConverter:", "SingleValueConverterWrapper", NULL, 0x1, NULL, NULL },
    { "canConvertWithIOSClass:", "canConvert", "Z", 0x1, NULL, NULL },
    { "toStringWithId:", "toString", "Ljava.lang.String;", 0x1, NULL, NULL },
    { "fromStringWithNSString:", "fromString", "Ljava.lang.Object;", 0x1, NULL, NULL },
    { "marshalWithId:withComThoughtworksXstreamIoHierarchicalStreamWriter:withComThoughtworksXstreamConvertersMarshallingContext:", "marshal", "V", 0x1, NULL, NULL },
    { "unmarshalWithComThoughtworksXstreamIoHierarchicalStreamReader:withComThoughtworksXstreamConvertersUnmarshallingContext:", "unmarshal", "Ljava.lang.Object;", 0x1, NULL, NULL },
    { "appendErrorsWithComThoughtworksXstreamConvertersErrorWriter:", "appendErrors", "V", 0x1, NULL, NULL },
  };
  static const J2ObjcFieldInfo fields[] = {
    { "wrapped_", NULL, 0x12, "Lcom.thoughtworks.xstream.converters.SingleValueConverter;", NULL, NULL,  },
  };
  static const J2ObjcClassInfo _ComThoughtworksXstreamConvertersSingleValueConverterWrapper = { 2, "SingleValueConverterWrapper", "com.thoughtworks.xstream.converters", NULL, 0x1, 7, methods, 1, fields, 0, NULL, 0, NULL, NULL, NULL };
  return &_ComThoughtworksXstreamConvertersSingleValueConverterWrapper;
}

@end


#line 28
void ComThoughtworksXstreamConvertersSingleValueConverterWrapper_initWithComThoughtworksXstreamConvertersSingleValueConverter_(ComThoughtworksXstreamConvertersSingleValueConverterWrapper *self, id<ComThoughtworksXstreamConvertersSingleValueConverter> wrapped) {
  (void) NSObject_init(self);
  
#line 29
  self->wrapped_ = wrapped;
}


#line 28
ComThoughtworksXstreamConvertersSingleValueConverterWrapper *new_ComThoughtworksXstreamConvertersSingleValueConverterWrapper_initWithComThoughtworksXstreamConvertersSingleValueConverter_(id<ComThoughtworksXstreamConvertersSingleValueConverter> wrapped) {
  ComThoughtworksXstreamConvertersSingleValueConverterWrapper *self = [ComThoughtworksXstreamConvertersSingleValueConverterWrapper alloc];
  ComThoughtworksXstreamConvertersSingleValueConverterWrapper_initWithComThoughtworksXstreamConvertersSingleValueConverter_(self, wrapped);
  return self;
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(ComThoughtworksXstreamConvertersSingleValueConverterWrapper)
