//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/Zetzsche/Development/SimarisCurves/com.thoughtworks.xstream/src/com/thoughtworks/xstream/persistence/PersistenceStrategy.java
//

#line 1 "/Users/Zetzsche/Development/SimarisCurves/com.thoughtworks.xstream/src/com/thoughtworks/xstream/persistence/PersistenceStrategy.java"

#include "com/thoughtworks/xstream/persistence/PersistenceStrategy.h"
#include "java/util/Iterator.h"

@interface ComThoughtworksXstreamPersistencePersistenceStrategy : NSObject
@end

@implementation ComThoughtworksXstreamPersistencePersistenceStrategy

+ (const J2ObjcClassInfo *)__metadata {
  static const J2ObjcMethodInfo methods[] = {
    { "iterator", NULL, "Ljava.util.Iterator;", 0x401, NULL },
    { "size", NULL, "I", 0x401, NULL },
    { "getWithId:", "get", "Ljava.lang.Object;", 0x401, NULL },
    { "putWithId:withId:", "put", "Ljava.lang.Object;", 0x401, NULL },
    { "removeWithId:", "remove", "Ljava.lang.Object;", 0x401, NULL },
  };
  static const J2ObjcClassInfo _ComThoughtworksXstreamPersistencePersistenceStrategy = { "PersistenceStrategy", "com.thoughtworks.xstream.persistence", NULL, 0x201, 5, methods, 0, NULL, 0, NULL};
  return &_ComThoughtworksXstreamPersistencePersistenceStrategy;
}

@end

