//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/Zetzsche/Development/SimarisCurves/com.thoughtworks.xstream/src/com/thoughtworks/xstream/persistence/XmlSet.java
//

#line 1 "/Users/Zetzsche/Development/SimarisCurves/com.thoughtworks.xstream/src/com/thoughtworks/xstream/persistence/XmlSet.java"

#include "com/thoughtworks/xstream/persistence/PersistenceStrategy.h"
#include "com/thoughtworks/xstream/persistence/XmlMap.h"
#include "com/thoughtworks/xstream/persistence/XmlSet.h"
#include "java/lang/Long.h"
#include "java/lang/System.h"
#include "java/util/Collection.h"
#include "java/util/Iterator.h"


#line 22
@implementation ComThoughtworksXstreamPersistenceXmlSet


#line 26
- (instancetype)initWithComThoughtworksXstreamPersistencePersistenceStrategy:(id<ComThoughtworksXstreamPersistencePersistenceStrategy>)persistenceStrategy {
  if (self = [super init]) {
    
#line 27
    self->map_ = [[ComThoughtworksXstreamPersistenceXmlMap alloc] initWithComThoughtworksXstreamPersistencePersistenceStrategy:persistenceStrategy];
  }
  return self;
}


#line 30
- (id<JavaUtilIterator>)iterator {
  
#line 31
  return [((id<JavaUtilCollection>) nil_chk([((ComThoughtworksXstreamPersistenceXmlMap *) nil_chk(map_)) values])) iterator];
}


#line 34
- (jint)size {
  
#line 35
  return [((ComThoughtworksXstreamPersistenceXmlMap *) nil_chk(map_)) size];
}


#line 38
- (jboolean)addWithId:(id)o {
  
#line 39
  if ([((ComThoughtworksXstreamPersistenceXmlMap *) nil_chk(map_)) containsValueWithId:o]) {
    return NO;
  }
  else {
    (void) [map_ putWithId:[self findEmptyKey] withId:o];
    return YES;
  }
}


#line 48
- (JavaLangLong *)findEmptyKey {
  
#line 49
  jlong i = [JavaLangSystem currentTimeMillis];
  while ([((ComThoughtworksXstreamPersistenceXmlMap *) nil_chk(map_)) containsKeyWithId:[[JavaLangLong alloc] initWithLong:i]]) {
    i++;
  }
  return [[JavaLangLong alloc] initWithLong:i];
}

- (void)copyAllFieldsTo:(ComThoughtworksXstreamPersistenceXmlSet *)other {
  [super copyAllFieldsTo:other];
  other->map_ = map_;
}

- (NSUInteger)countByEnumeratingWithState:(NSFastEnumerationState *)state objects:(__unsafe_unretained id *)stackbuf count:(NSUInteger)len {
  return JreDefaultFastEnumeration(self, state, stackbuf, len);
}

+ (const J2ObjcClassInfo *)__metadata {
  static const J2ObjcMethodInfo methods[] = {
    { "initWithComThoughtworksXstreamPersistencePersistenceStrategy:", "XmlSet", NULL, 0x1, NULL },
    { "iterator", NULL, "Ljava.util.Iterator;", 0x1, NULL },
    { "size", NULL, "I", 0x1, NULL },
    { "addWithId:", "add", "Z", 0x1, NULL },
    { "findEmptyKey", NULL, "Ljava.lang.Long;", 0x2, NULL },
  };
  static const J2ObjcFieldInfo fields[] = {
    { "map_", NULL, 0x12, "Lcom.thoughtworks.xstream.persistence.XmlMap;", NULL,  },
  };
  static const J2ObjcClassInfo _ComThoughtworksXstreamPersistenceXmlSet = { "XmlSet", "com.thoughtworks.xstream.persistence", NULL, 0x1, 5, methods, 1, fields, 0, NULL};
  return &_ComThoughtworksXstreamPersistenceXmlSet;
}

@end
