//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/Zetzsche/Development/SimarisCurves/com.thoughtworks.xstream/src/com/thoughtworks/xstream/converters/basic/AbstractSingleValueConverter.java
//

#ifndef _ComThoughtworksXstreamConvertersBasicAbstractSingleValueConverter_H_
#define _ComThoughtworksXstreamConvertersBasicAbstractSingleValueConverter_H_

@class IOSClass;

#import "JreEmulation.h"
#include "com/thoughtworks/xstream/converters/SingleValueConverter.h"

@interface ComThoughtworksXstreamConvertersBasicAbstractSingleValueConverter : NSObject < ComThoughtworksXstreamConvertersSingleValueConverter > {
}

- (jboolean)canConvertWithIOSClass:(IOSClass *)type;

- (NSString *)toStringWithId:(id)obj;

- (id)fromStringWithNSString:(NSString *)str;

- (instancetype)init;

@end

__attribute__((always_inline)) inline void ComThoughtworksXstreamConvertersBasicAbstractSingleValueConverter_init() {}

#endif // _ComThoughtworksXstreamConvertersBasicAbstractSingleValueConverter_H_
